/*
###############################################################
#  Generated by:      Cadence Innovus 21.18-s099_1
#  OS:                Linux x86_64(Host ID c2slab.cet.ac.in)
#  Generated on:      Wed Mar  5 14:03:21 2025
#  Design:            fifo_top
#  Command:           saveNetlist -includePowerGround ./Signoff/fifo_signoff_withPG.v
###############################################################
*/
module bufbd7 (
	I, 
	Z, 
	VSS, 
	VDD);
   input I;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module buffd3 (
	I, 
	Z, 
	VSS, 
	VDD);
   input I;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module dl02d1 (
	I, 
	Z, 
	VSS, 
	VDD);
   input I;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module inv0d0 (
	I, 
	ZN, 
	VSS, 
	VDD);
   input I;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module dfcrq1 (
	CDN, 
	CP, 
	D, 
	Q, 
	VSS, 
	VDD);
   input CDN;
   input CP;
   input D;
   output Q;
   inout VSS;
   inout VDD;
endmodule

module mx02d1 (
	I0, 
	I1, 
	S, 
	Z, 
	VSS, 
	VDD);
   input I0;
   input I1;
   input S;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module aoim22d1 (
	A1, 
	A2, 
	B1, 
	B2, 
	Z, 
	VSS, 
	VDD);
   input A1;
   input A2;
   input B1;
   input B2;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module xr02d1 (
	A1, 
	A2, 
	Z, 
	VSS, 
	VDD);
   input A1;
   input A2;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module ah01d1 (
	A, 
	B, 
	CO, 
	S, 
	VSS, 
	VDD);
   input A;
   input B;
   output CO;
   output S;
   inout VSS;
   inout VDD;
endmodule

module nr02d1 (
	A1, 
	A2, 
	ZN, 
	VSS, 
	VDD);
   input A1;
   input A2;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module dfprb1 (
	CP, 
	D, 
	Q, 
	QN, 
	SDN, 
	VSS, 
	VDD);
   input CP;
   input D;
   output Q;
   output QN;
   input SDN;
   inout VSS;
   inout VDD;
endmodule

module oan211d1 (
	A, 
	B, 
	C1, 
	C2, 
	ZN, 
	VSS, 
	VDD);
   input A;
   input B;
   input C1;
   input C2;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module nd04d1 (
	A1, 
	A2, 
	A3, 
	A4, 
	ZN, 
	VSS, 
	VDD);
   input A1;
   input A2;
   input A3;
   input A4;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module oaim22d1 (
	A1, 
	A2, 
	B1, 
	B2, 
	ZN, 
	VSS, 
	VDD);
   input A1;
   input A2;
   input B1;
   input B2;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module nd02d1 (
	A1, 
	A2, 
	ZN, 
	VSS, 
	VDD);
   input A1;
   input A2;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module dfcrb1 (
	CDN, 
	CP, 
	D, 
	Q, 
	QN, 
	VSS, 
	VDD);
   input CDN;
   input CP;
   input D;
   output Q;
   output QN;
   inout VSS;
   inout VDD;
endmodule

module dl01d1 (
	I, 
	Z, 
	VSS, 
	VDD);
   input I;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module buffd1 (
	I, 
	Z, 
	VSS, 
	VDD);
   input I;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module nr04d1 (
	A1, 
	A2, 
	A3, 
	A4, 
	ZN, 
	VSS, 
	VDD);
   input A1;
   input A2;
   input A3;
   input A4;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module oai211d1 (
	A, 
	B, 
	C1, 
	C2, 
	ZN, 
	VSS, 
	VDD);
   input A;
   input B;
   input C1;
   input C2;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module buffd7 (
	I, 
	Z, 
	VSS, 
	VDD);
   input I;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module aoi221d1 (
	A, 
	B1, 
	B2, 
	C1, 
	C2, 
	ZN, 
	VSS, 
	VDD);
   input A;
   input B1;
   input B2;
   input C1;
   input C2;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module aoi222d1 (
	A1, 
	A2, 
	B1, 
	B2, 
	C1, 
	C2, 
	ZN, 
	VSS, 
	VDD);
   input A1;
   input A2;
   input B1;
   input B2;
   input C1;
   input C2;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module aoi22d1 (
	A1, 
	A2, 
	B1, 
	B2, 
	ZN, 
	VSS, 
	VDD);
   input A1;
   input A2;
   input B1;
   input B2;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module nd12d1 (
	A1, 
	A2, 
	ZN, 
	VSS, 
	VDD);
   input A1;
   input A2;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module or02d1 (
	A1, 
	A2, 
	Z, 
	VSS, 
	VDD);
   input A1;
   input A2;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module decrq1 (
	CDN, 
	CP, 
	D, 
	ENN, 
	Q, 
	VSS, 
	VDD);
   input CDN;
   input CP;
   input D;
   input ENN;
   output Q;
   inout VSS;
   inout VDD;
endmodule

module an12d1 (
	A1, 
	A2, 
	Z, 
	VSS, 
	VDD);
   input A1;
   input A2;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module dl03d1 (
	I, 
	Z, 
	VSS, 
	VDD);
   input I;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module pc3c01 (
	CCLK, 
	CP, 
	VSSO, 
	VSS, 
	VDDO, 
	VDD);
   input CCLK;
   output CP;
   inout VSSO;
   inout VSS;
   inout VDDO;
   inout VDD;
endmodule

module pc3d01 (
	PAD, 
	CIN, 
	VSSO, 
	VSS, 
	VDDO, 
	VDD);
   input PAD;
   output CIN;
   inout VSSO;
   inout VSS;
   inout VDDO;
   inout VDD;
endmodule

module pc3o05 (
	I, 
	PAD, 
	VSSO, 
	VSS, 
	VDDO, 
	VDD);
   input I;
   output PAD;
   inout VSSO;
   inout VSS;
   inout VDDO;
   inout VDD;
endmodule

module pvdi (
	VSSO, 
	VSS, 
	VDDO, 
	VDD);
   inout VSSO;
   inout VSS;
   inout VDDO;
   output VDD;
endmodule

module pv0i (
	VSSO, 
	VSS, 
	VDDO, 
	VDD);
   inout VSSO;
   output VSS;
   inout VDDO;
   inout VDD;
endmodule

module pvda (
	VSSO, 
	VSS, 
	VDDO, 
	VDD);
   inout VSSO;
   inout VSS;
   output VDDO;
   inout VDD;
endmodule

module pv0a (
	VSSO, 
	VSS, 
	VDDO, 
	VDD);
   output VSSO;
   inout VSS;
   inout VDDO;
   inout VDD;
endmodule

module fifo_empty (
	rd_clk, 
	rd_en, 
	rd_rst, 
	wr_ptr_addr_sync, 
	empty, 
	rd_addr_grey, 
	rd_addr_bin, 
	VDD_CORE, 
	VSS_CORE);
   input rd_clk;
   input rd_en;
   input rd_rst;
   input [4:0] wr_ptr_addr_sync;
   output empty;
   output [4:0] rd_addr_grey;
   output [3:0] rd_addr_bin;
   inout VDD_CORE;
   inout VSS_CORE;

   // Internal wires
   wire FE_PHN17_n_9;
   wire FE_PHN4_n_10;
   wire FE_PHN3_rd_addr_3;
   wire FE_PHN2_rd_addr_1;
   wire FE_PHN1_rd_addr_2;
   wire FE_PHN0_rd_addr_0;
   wire FE_OFN8_empty;
   wire [4:0] rd_addr_grey_next;
   wire [4:0] rd_addr_bin_next;
   wire UNCONNECTED;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;

   // Module instantiations
   dl02d1 FE_PHC17_n_9 (
	.I(n_9),
	.Z(FE_PHN17_n_9), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dl02d1 FE_PHC4_n_10 (
	.I(n_10),
	.Z(FE_PHN4_n_10), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dl02d1 FE_PHC3_rd_addr_3 (
	.I(rd_addr_bin[3]),
	.Z(FE_PHN3_rd_addr_3), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dl02d1 FE_PHC2_rd_addr_1 (
	.I(rd_addr_bin[1]),
	.Z(FE_PHN2_rd_addr_1), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dl02d1 FE_PHC1_rd_addr_2 (
	.I(rd_addr_bin[2]),
	.Z(FE_PHN1_rd_addr_2), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dl02d1 FE_PHC0_rd_addr_0 (
	.I(rd_addr_bin[0]),
	.Z(FE_PHN0_rd_addr_0), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   buffd3 FE_OFC8_empty (
	.I(FE_OFN8_empty),
	.Z(empty), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   inv0d0 g137 (
	.I(rd_en),
	.ZN(n_17), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \rd_addr_grey_reg[3]  (
	.CDN(rd_rst),
	.CP(rd_clk),
	.D(rd_addr_grey_next[3]),
	.Q(rd_addr_grey[3]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   mx02d1 g184__2398 (
	.I0(rd_addr_bin_next[4]),
	.I1(n_16),
	.S(rd_addr_bin_next[3]),
	.Z(rd_addr_grey_next[3]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \rd_addr_grey_reg[2]  (
	.CDN(rd_rst),
	.CP(rd_clk),
	.D(rd_addr_grey_next[2]),
	.Q(rd_addr_grey[2]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   inv0d0 g186 (
	.I(n_16),
	.ZN(rd_addr_bin_next[4]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoim22d1 g187__5107 (
	.A1(n_15),
	.A2(FE_PHN4_n_10),
	.B1(n_15),
	.B2(FE_PHN4_n_10),
	.Z(n_16), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   xr02d1 g188__6260 (
	.A1(rd_addr_bin_next[3]),
	.A2(rd_addr_bin_next[2]),
	.Z(rd_addr_grey_next[2]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   ah01d1 g189__4319 (
	.A(n_14),
	.B(FE_PHN3_rd_addr_3),
	.CO(n_15),
	.S(rd_addr_bin_next[3]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \rd_addr_grey_reg[1]  (
	.CDN(rd_rst),
	.CP(rd_clk),
	.D(rd_addr_grey_next[1]),
	.Q(rd_addr_grey[1]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   xr02d1 g191__8428 (
	.A1(rd_addr_bin_next[2]),
	.A2(rd_addr_bin_next[1]),
	.Z(rd_addr_grey_next[1]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   ah01d1 g192__5526 (
	.A(n_13),
	.B(FE_PHN1_rd_addr_2),
	.CO(n_14),
	.S(rd_addr_bin_next[2]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \rd_addr_grey_reg[0]  (
	.CDN(rd_rst),
	.CP(rd_clk),
	.D(rd_addr_grey_next[0]),
	.Q(rd_addr_grey[0]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   xr02d1 g194__6783 (
	.A1(rd_addr_bin_next[1]),
	.A2(rd_addr_bin_next[0]),
	.Z(rd_addr_grey_next[0]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   ah01d1 g195__3680 (
	.A(n_12),
	.B(FE_PHN2_rd_addr_1),
	.CO(n_13),
	.S(rd_addr_bin_next[1]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   ah01d1 g196__1617 (
	.A(n_11),
	.B(FE_PHN0_rd_addr_0),
	.CO(n_12),
	.S(rd_addr_bin_next[0]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g197__2802 (
	.A1(empty),
	.A2(n_17),
	.ZN(n_11), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfprb1 empty_r_reg (
	.CP(rd_clk),
	.D(FE_PHN17_n_9),
	.Q(FE_OFN8_empty),
	.QN(UNCONNECTED),
	.SDN(rd_rst), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   oan211d1 g199__1705 (
	.A(n_8),
	.B(n_3),
	.C1(rd_addr_bin_next[4]),
	.C2(wr_ptr_addr_sync[4]),
	.ZN(n_9), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd04d1 g200__5122 (
	.A1(n_5),
	.A2(n_7),
	.A3(n_4),
	.A4(n_6),
	.ZN(n_8), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   oaim22d1 g201__8246 (
	.A1(rd_addr_grey_next[3]),
	.A2(wr_ptr_addr_sync[3]),
	.B1(rd_addr_grey_next[3]),
	.B2(wr_ptr_addr_sync[3]),
	.ZN(n_7), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoim22d1 g202__7098 (
	.A1(rd_addr_grey_next[0]),
	.A2(n_1),
	.B1(rd_addr_grey_next[0]),
	.B2(n_1),
	.Z(n_6), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoim22d1 g203__6131 (
	.A1(rd_addr_grey_next[1]),
	.A2(n_2),
	.B1(rd_addr_grey_next[1]),
	.B2(n_2),
	.Z(n_5), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoim22d1 g204__1881 (
	.A1(rd_addr_grey_next[2]),
	.A2(n_0),
	.B1(rd_addr_grey_next[2]),
	.B2(n_0),
	.Z(n_4), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \rd_addr_bin_r_reg[0]  (
	.CDN(rd_rst),
	.CP(rd_clk),
	.D(rd_addr_bin_next[0]),
	.Q(rd_addr_bin[0]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \rd_addr_bin_r_reg[1]  (
	.CDN(rd_rst),
	.CP(rd_clk),
	.D(rd_addr_bin_next[1]),
	.Q(rd_addr_bin[1]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \rd_addr_bin_r_reg[2]  (
	.CDN(rd_rst),
	.CP(rd_clk),
	.D(rd_addr_bin_next[2]),
	.Q(rd_addr_bin[2]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \rd_addr_bin_r_reg[3]  (
	.CDN(rd_rst),
	.CP(rd_clk),
	.D(rd_addr_bin_next[3]),
	.Q(rd_addr_bin[3]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 g208__5115 (
	.A1(rd_addr_bin_next[4]),
	.A2(wr_ptr_addr_sync[4]),
	.ZN(n_3), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   inv0d0 g209 (
	.I(wr_ptr_addr_sync[1]),
	.ZN(n_2), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   inv0d0 g210 (
	.I(wr_ptr_addr_sync[0]),
	.ZN(n_1), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   inv0d0 g211 (
	.I(wr_ptr_addr_sync[2]),
	.ZN(n_0), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrb1 \rd_addr_bin_r_reg[4]  (
	.CDN(rd_rst),
	.CP(rd_clk),
	.D(rd_addr_bin_next[4]),
	.Q(rd_addr_grey[4]),
	.QN(n_10), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
endmodule

module fifo_full (
	wr_en, 
	wr_rst, 
	rd_ptr_addr_sync, 
	full, 
	wr_addr_grey, 
	wr_addr_bin, 
	wr_clk, 
	VDD_CORE, 
	VSS_CORE);
   input wr_en;
   input wr_rst;
   input [4:0] rd_ptr_addr_sync;
   output full;
   output [4:0] wr_addr_grey;
   output [3:0] wr_addr_bin;
   input wr_clk;
   inout VDD_CORE;
   inout VSS_CORE;

   // Internal wires
   wire FE_PHN20_n_8;
   wire FE_PHN19_wr_addr_binary_next_1;
   wire FE_PHN18_wr_addr_binary_next_2;
   wire FE_PHN16_wr_addr_grey_4;
   wire FE_OFN9_full;
   wire [4:0] wr_addr_grey_next;
   wire [4:0] wr_addr_binary_next;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;

   // Module instantiations
   dl01d1 FE_PHC20_n_8 (
	.I(n_8),
	.Z(FE_PHN20_n_8), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   buffd1 FE_PHC19_wr_addr_binary_next_1 (
	.I(wr_addr_binary_next[1]),
	.Z(FE_PHN19_wr_addr_binary_next_1), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   buffd1 FE_PHC18_wr_addr_binary_next_2 (
	.I(wr_addr_binary_next[2]),
	.Z(FE_PHN18_wr_addr_binary_next_2), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   buffd1 FE_PHC16_wr_addr_grey_4 (
	.I(wr_addr_grey[4]),
	.Z(FE_PHN16_wr_addr_grey_4), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   buffd3 FE_OFC9_full (
	.I(FE_OFN9_full),
	.Z(full), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   inv0d0 g162 (
	.I(wr_en),
	.ZN(n_16), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \wr_addr_grey_reg[3]  (
	.CDN(wr_rst),
	.CP(wr_clk),
	.D(wr_addr_grey_next[3]),
	.Q(wr_addr_grey[3]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   mx02d1 g212__7482 (
	.I0(wr_addr_binary_next[4]),
	.I1(n_15),
	.S(wr_addr_binary_next[3]),
	.Z(wr_addr_grey_next[3]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \wr_addr_grey_reg[2]  (
	.CDN(wr_rst),
	.CP(wr_clk),
	.D(wr_addr_grey_next[2]),
	.Q(wr_addr_grey[2]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   inv0d0 g214 (
	.I(n_15),
	.ZN(wr_addr_binary_next[4]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoim22d1 g215__4733 (
	.A1(n_14),
	.A2(FE_PHN16_wr_addr_grey_4),
	.B1(n_14),
	.B2(wr_addr_grey[4]),
	.Z(n_15), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   xr02d1 g216__6161 (
	.A1(wr_addr_binary_next[3]),
	.A2(wr_addr_binary_next[2]),
	.Z(wr_addr_grey_next[2]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   inv0d0 g217 (
	.I(n_13),
	.ZN(n_14), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   ah01d1 g218__9315 (
	.A(n_12),
	.B(wr_addr_bin[3]),
	.CO(n_13),
	.S(wr_addr_binary_next[3]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \wr_addr_grey_reg[1]  (
	.CDN(wr_rst),
	.CP(wr_clk),
	.D(wr_addr_grey_next[1]),
	.Q(wr_addr_grey[1]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   xr02d1 g220__9945 (
	.A1(wr_addr_binary_next[2]),
	.A2(wr_addr_binary_next[1]),
	.Z(wr_addr_grey_next[1]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   ah01d1 g221__2883 (
	.A(n_11),
	.B(wr_addr_bin[2]),
	.CO(n_12),
	.S(wr_addr_binary_next[2]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \wr_addr_grey_reg[0]  (
	.CDN(wr_rst),
	.CP(wr_clk),
	.D(wr_addr_grey_next[0]),
	.Q(wr_addr_grey[0]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   xr02d1 g223__2346 (
	.A1(wr_addr_binary_next[1]),
	.A2(wr_addr_binary_next[0]),
	.Z(wr_addr_grey_next[0]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   ah01d1 g224__1666 (
	.A(n_10),
	.B(wr_addr_bin[1]),
	.CO(n_11),
	.S(wr_addr_binary_next[1]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   ah01d1 g225__7410 (
	.A(n_9),
	.B(wr_addr_bin[0]),
	.CO(n_10),
	.S(wr_addr_binary_next[0]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g226__6417 (
	.A1(full),
	.A2(n_16),
	.ZN(n_9), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 full_r_reg (
	.CDN(wr_rst),
	.CP(wr_clk),
	.D(FE_PHN20_n_8),
	.Q(FE_OFN9_full), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr04d1 g227__5477 (
	.A1(n_5),
	.A2(n_4),
	.A3(n_6),
	.A4(n_7),
	.ZN(n_8), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   oai211d1 g228__2398 (
	.A(n_2),
	.B(n_3),
	.C1(wr_addr_grey_next[3]),
	.C2(rd_ptr_addr_sync[3]),
	.ZN(n_7), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoim22d1 g229__5107 (
	.A1(wr_addr_grey_next[2]),
	.A2(rd_ptr_addr_sync[2]),
	.B1(wr_addr_grey_next[2]),
	.B2(rd_ptr_addr_sync[2]),
	.Z(n_6), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoim22d1 g230__6260 (
	.A1(wr_addr_grey_next[0]),
	.A2(rd_ptr_addr_sync[0]),
	.B1(wr_addr_grey_next[0]),
	.B2(rd_ptr_addr_sync[0]),
	.Z(n_5), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoim22d1 g231__4319 (
	.A1(wr_addr_binary_next[4]),
	.A2(n_0),
	.B1(wr_addr_binary_next[4]),
	.B2(n_0),
	.Z(n_4), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoim22d1 g232__8428 (
	.A1(n_1),
	.A2(rd_ptr_addr_sync[1]),
	.B1(n_1),
	.B2(rd_ptr_addr_sync[1]),
	.Z(n_3), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \wr_addr_bin_r_reg[0]  (
	.CDN(wr_rst),
	.CP(wr_clk),
	.D(wr_addr_binary_next[0]),
	.Q(wr_addr_bin[0]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \wr_addr_bin_r_reg[1]  (
	.CDN(wr_rst),
	.CP(wr_clk),
	.D(FE_PHN19_wr_addr_binary_next_1),
	.Q(wr_addr_bin[1]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \wr_addr_bin_r_reg[2]  (
	.CDN(wr_rst),
	.CP(wr_clk),
	.D(FE_PHN18_wr_addr_binary_next_2),
	.Q(wr_addr_bin[2]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \wr_addr_bin_r_reg[4]  (
	.CDN(wr_rst),
	.CP(wr_clk),
	.D(wr_addr_binary_next[4]),
	.Q(wr_addr_grey[4]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \wr_addr_bin_r_reg[3]  (
	.CDN(wr_rst),
	.CP(wr_clk),
	.D(wr_addr_binary_next[3]),
	.Q(wr_addr_bin[3]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 g237__5526 (
	.A1(wr_addr_grey_next[3]),
	.A2(rd_ptr_addr_sync[3]),
	.ZN(n_2), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   inv0d0 g238 (
	.I(wr_addr_grey_next[1]),
	.ZN(n_1), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   inv0d0 g239 (
	.I(rd_ptr_addr_sync[4]),
	.ZN(n_0), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
endmodule

module fifo_memory (
	rst, 
	wr_en, 
	full, 
	wr_addr, 
	rd_addr, 
	wr_data, 
	rd_data, 
	FE_OFN0_wr_rst, 
	clk_clone1, 
	clk, 
	VDD_CORE, 
	VSS_CORE);
   input rst;
   input wr_en;
   input full;
   input [3:0] wr_addr;
   input [3:0] rd_addr;
   input [7:0] wr_data;
   output [7:0] rd_data;
   input FE_OFN0_wr_rst;
   input clk_clone1;
   input clk;
   inout VDD_CORE;
   inout VSS_CORE;

   // Internal wires
   wire FE_PHN21_wr_addr_0;
   wire FE_PHN15_wr_addr_0;
   wire CTS_1;
   wire FE_OFN11_wr_rst;
   wire [7:0] \mem[8] ;
   wire [7:0] \mem[9] ;
   wire [7:0] \mem[0] ;
   wire [7:0] \mem[1] ;
   wire [7:0] \mem[4] ;
   wire [7:0] \mem[5] ;
   wire [7:0] \mem[2] ;
   wire [7:0] \mem[3] ;
   wire [7:0] \mem[14] ;
   wire [7:0] \mem[15] ;
   wire [7:0] \mem[10] ;
   wire [7:0] \mem[11] ;
   wire [7:0] \mem[6] ;
   wire [7:0] \mem[7] ;
   wire [7:0] \mem[12] ;
   wire [7:0] \mem[13] ;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_89;
   wire n_90;
   wire n_91;
   wire n_92;
   wire n_93;
   wire n_94;
   wire n_95;
   wire n_96;
   wire n_97;
   wire n_98;
   wire n_99;
   wire n_100;
   wire n_101;
   wire n_102;
   wire n_103;
   wire n_104;
   wire n_105;
   wire n_106;
   wire n_107;
   wire n_108;
   wire n_109;
   wire n_110;
   wire n_111;
   wire n_112;
   wire n_113;
   wire n_114;
   wire n_115;
   wire n_116;
   wire n_117;
   wire n_118;
   wire n_119;
   wire n_120;
   wire n_121;
   wire n_122;
   wire n_123;
   wire n_124;
   wire n_125;
   wire n_126;
   wire n_127;
   wire n_128;

   // Module instantiations
   buffd1 FE_PHC21_wr_addr_0 (
	.I(wr_addr[0]),
	.Z(FE_PHN21_wr_addr_0), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   buffd7 FE_PHC15_wr_addr_0 (
	.I(wr_addr[0]),
	.Z(FE_PHN15_wr_addr_0), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   bufbd7 CTS_ccl_a_buf_00062 (
	.I(clk),
	.Z(CTS_1), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   buffd3 FE_OFC11_wr_rst (
	.I(rst),
	.Z(FE_OFN11_wr_rst), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd04d1 g3106__6783 (
	.A1(n_103),
	.A2(n_128),
	.A3(n_111),
	.A4(n_64),
	.ZN(rd_data[2]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd04d1 g3107__3680 (
	.A1(n_94),
	.A2(n_122),
	.A3(n_106),
	.A4(n_59),
	.ZN(rd_data[6]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd04d1 g3108__1617 (
	.A1(n_70),
	.A2(n_126),
	.A3(n_112),
	.A4(n_57),
	.ZN(rd_data[7]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd04d1 g3109__2802 (
	.A1(n_95),
	.A2(n_125),
	.A3(n_109),
	.A4(n_61),
	.ZN(rd_data[1]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd04d1 g3110__1705 (
	.A1(n_66),
	.A2(n_127),
	.A3(n_110),
	.A4(n_63),
	.ZN(rd_data[5]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd04d1 g3111__5122 (
	.A1(n_85),
	.A2(n_124),
	.A3(n_108),
	.A4(n_62),
	.ZN(rd_data[0]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd04d1 g3112__8246 (
	.A1(n_89),
	.A2(n_123),
	.A3(n_107),
	.A4(n_58),
	.ZN(rd_data[4]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd04d1 g3113__7098 (
	.A1(n_73),
	.A2(n_121),
	.A3(n_105),
	.A4(n_60),
	.ZN(rd_data[3]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi221d1 g3114__6131 (
	.A(n_118),
	.B1(n_42),
	.B2(\mem[8] [2]),
	.C1(\mem[9] [2]),
	.C2(n_46),
	.ZN(n_128), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi221d1 g3115__1881 (
	.A(n_119),
	.B1(n_41),
	.B2(\mem[0] [5]),
	.C1(\mem[1] [5]),
	.C2(n_51),
	.ZN(n_127), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi221d1 g3116__5115 (
	.A(n_117),
	.B1(n_56),
	.B2(\mem[4] [7]),
	.C1(\mem[5] [7]),
	.C2(n_53),
	.ZN(n_126), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi221d1 g3117__7482 (
	.A(n_120),
	.B1(n_54),
	.B2(\mem[2] [1]),
	.C1(\mem[3] [1]),
	.C2(n_47),
	.ZN(n_125), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi221d1 g3118__4733 (
	.A(n_114),
	.B1(n_54),
	.B2(\mem[2] [0]),
	.C1(\mem[3] [0]),
	.C2(n_47),
	.ZN(n_124), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi221d1 g3119__6161 (
	.A(n_115),
	.B1(n_55),
	.B2(\mem[14] [4]),
	.C1(\mem[15] [4]),
	.C2(n_52),
	.ZN(n_123), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi221d1 g3120__9315 (
	.A(n_116),
	.B1(n_44),
	.B2(\mem[10] [6]),
	.C1(\mem[11] [6]),
	.C2(n_48),
	.ZN(n_122), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi221d1 g3121__9945 (
	.A(n_113),
	.B1(n_45),
	.B2(\mem[6] [3]),
	.C1(\mem[7] [3]),
	.C2(n_50),
	.ZN(n_121), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd04d1 g3122__2883 (
	.A1(n_87),
	.A2(n_91),
	.A3(n_88),
	.A4(n_90),
	.ZN(n_120), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd04d1 g3123__2346 (
	.A1(n_99),
	.A2(n_93),
	.A3(n_92),
	.A4(n_96),
	.ZN(n_119), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd04d1 g3124__1666 (
	.A1(n_100),
	.A2(n_98),
	.A3(n_97),
	.A4(n_101),
	.ZN(n_118), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd04d1 g3125__7410 (
	.A1(n_102),
	.A2(n_68),
	.A3(n_86),
	.A4(n_76),
	.ZN(n_117), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd04d1 g3126__6417 (
	.A1(n_80),
	.A2(n_72),
	.A3(n_71),
	.A4(n_75),
	.ZN(n_116), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd04d1 g3127__5477 (
	.A1(n_74),
	.A2(n_77),
	.A3(n_79),
	.A4(n_83),
	.ZN(n_115), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd04d1 g3128__2398 (
	.A1(n_78),
	.A2(n_82),
	.A3(n_81),
	.A4(n_84),
	.ZN(n_114), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd04d1 g3129__5107 (
	.A1(n_67),
	.A2(n_65),
	.A3(n_104),
	.A4(n_69),
	.ZN(n_113), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi222d1 g3130__6260 (
	.A1(\mem[1] [7]),
	.A2(n_51),
	.B1(n_45),
	.B2(\mem[6] [7]),
	.C1(\mem[7] [7]),
	.C2(n_50),
	.ZN(n_112), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi222d1 g3131__4319 (
	.A1(\mem[10] [2]),
	.A2(n_44),
	.B1(n_55),
	.B2(\mem[14] [2]),
	.C1(\mem[11] [2]),
	.C2(n_48),
	.ZN(n_111), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi222d1 g3132__8428 (
	.A1(\mem[2] [5]),
	.A2(n_54),
	.B1(n_45),
	.B2(\mem[6] [5]),
	.C1(\mem[3] [5]),
	.C2(n_47),
	.ZN(n_110), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi222d1 g3133__5526 (
	.A1(\mem[4] [1]),
	.A2(n_56),
	.B1(n_50),
	.B2(\mem[7] [1]),
	.C1(\mem[5] [1]),
	.C2(n_53),
	.ZN(n_109), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi222d1 g3134__6783 (
	.A1(\mem[4] [0]),
	.A2(n_56),
	.B1(n_50),
	.B2(\mem[7] [0]),
	.C1(\mem[5] [0]),
	.C2(n_53),
	.ZN(n_108), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi222d1 g3135__3680 (
	.A1(\mem[10] [4]),
	.A2(n_44),
	.B1(n_42),
	.B2(\mem[8] [4]),
	.C1(\mem[9] [4]),
	.C2(n_46),
	.ZN(n_107), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi222d1 g3136__1617 (
	.A1(\mem[8] [6]),
	.A2(n_42),
	.B1(n_49),
	.B2(\mem[12] [6]),
	.C1(\mem[13] [6]),
	.C2(n_43),
	.ZN(n_106), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi222d1 g3137__2802 (
	.A1(\mem[0] [3]),
	.A2(n_41),
	.B1(n_47),
	.B2(\mem[3] [3]),
	.C1(\mem[1] [3]),
	.C2(n_51),
	.ZN(n_105), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g3138__1705 (
	.A1(n_44),
	.A2(\mem[10] [3]),
	.B1(n_48),
	.B2(\mem[11] [3]),
	.ZN(n_104), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g3139__5122 (
	.A1(n_49),
	.A2(\mem[12] [2]),
	.B1(n_52),
	.B2(\mem[15] [2]),
	.ZN(n_103), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g3140__8246 (
	.A1(n_49),
	.A2(\mem[12] [7]),
	.B1(n_43),
	.B2(\mem[13] [7]),
	.ZN(n_102), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g3141__7098 (
	.A1(n_45),
	.A2(\mem[6] [2]),
	.B1(n_50),
	.B2(\mem[7] [2]),
	.ZN(n_101), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g3142__6131 (
	.A1(n_56),
	.A2(\mem[4] [2]),
	.B1(n_53),
	.B2(\mem[5] [2]),
	.ZN(n_100), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g3143__1881 (
	.A1(n_42),
	.A2(\mem[8] [5]),
	.B1(n_46),
	.B2(\mem[9] [5]),
	.ZN(n_99), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g3144__5115 (
	.A1(n_54),
	.A2(\mem[2] [2]),
	.B1(n_47),
	.B2(\mem[3] [2]),
	.ZN(n_98), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g3145__7482 (
	.A1(n_41),
	.A2(\mem[0] [2]),
	.B1(n_51),
	.B2(\mem[1] [2]),
	.ZN(n_97), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g3146__4733 (
	.A1(n_49),
	.A2(\mem[12] [5]),
	.B1(n_43),
	.B2(\mem[13] [5]),
	.ZN(n_96), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g3147__6161 (
	.A1(n_41),
	.A2(\mem[0] [1]),
	.B1(n_45),
	.B2(\mem[6] [1]),
	.ZN(n_95), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g3148__9315 (
	.A1(n_46),
	.A2(\mem[9] [6]),
	.B1(n_55),
	.B2(\mem[14] [6]),
	.ZN(n_94), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g3149__9945 (
	.A1(n_55),
	.A2(\mem[14] [5]),
	.B1(n_52),
	.B2(\mem[15] [5]),
	.ZN(n_93), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g3150__2883 (
	.A1(n_44),
	.A2(\mem[10] [5]),
	.B1(n_48),
	.B2(\mem[11] [5]),
	.ZN(n_92), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g3151__2346 (
	.A1(n_55),
	.A2(\mem[14] [1]),
	.B1(n_52),
	.B2(\mem[15] [1]),
	.ZN(n_91), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g3152__1666 (
	.A1(n_49),
	.A2(\mem[12] [1]),
	.B1(n_43),
	.B2(\mem[13] [1]),
	.ZN(n_90), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g3153__7410 (
	.A1(n_49),
	.A2(\mem[12] [4]),
	.B1(n_48),
	.B2(\mem[11] [4]),
	.ZN(n_89), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g3154__6417 (
	.A1(n_44),
	.A2(\mem[10] [1]),
	.B1(n_48),
	.B2(\mem[11] [1]),
	.ZN(n_88), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g3155__5477 (
	.A1(n_42),
	.A2(\mem[8] [1]),
	.B1(n_46),
	.B2(\mem[9] [1]),
	.ZN(n_87), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g3156__2398 (
	.A1(n_44),
	.A2(\mem[10] [7]),
	.B1(n_48),
	.B2(\mem[11] [7]),
	.ZN(n_86), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g3157__5107 (
	.A1(n_51),
	.A2(\mem[1] [0]),
	.B1(n_45),
	.B2(\mem[6] [0]),
	.ZN(n_85), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g3158__6260 (
	.A1(n_49),
	.A2(\mem[12] [0]),
	.B1(n_43),
	.B2(\mem[13] [0]),
	.ZN(n_84), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g3159__4319 (
	.A1(n_45),
	.A2(\mem[6] [4]),
	.B1(n_50),
	.B2(\mem[7] [4]),
	.ZN(n_83), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g3160__8428 (
	.A1(n_55),
	.A2(\mem[14] [0]),
	.B1(n_52),
	.B2(\mem[15] [0]),
	.ZN(n_82), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g3161__5526 (
	.A1(n_44),
	.A2(\mem[10] [0]),
	.B1(n_48),
	.B2(\mem[11] [0]),
	.ZN(n_81), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g3162__6783 (
	.A1(n_56),
	.A2(\mem[4] [6]),
	.B1(n_53),
	.B2(\mem[5] [6]),
	.ZN(n_80), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g3163__3680 (
	.A1(n_41),
	.A2(\mem[0] [4]),
	.B1(n_51),
	.B2(\mem[1] [4]),
	.ZN(n_79), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g3164__1617 (
	.A1(n_42),
	.A2(\mem[8] [0]),
	.B1(n_46),
	.B2(\mem[9] [0]),
	.ZN(n_78), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g3165__2802 (
	.A1(n_54),
	.A2(\mem[2] [4]),
	.B1(n_47),
	.B2(\mem[3] [4]),
	.ZN(n_77), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g3166__1705 (
	.A1(n_42),
	.A2(\mem[8] [7]),
	.B1(n_46),
	.B2(\mem[9] [7]),
	.ZN(n_76), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g3167__5122 (
	.A1(n_45),
	.A2(\mem[6] [6]),
	.B1(n_50),
	.B2(\mem[7] [6]),
	.ZN(n_75), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g3168__8246 (
	.A1(n_56),
	.A2(\mem[4] [4]),
	.B1(n_53),
	.B2(\mem[5] [4]),
	.ZN(n_74), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g3169__7098 (
	.A1(n_56),
	.A2(\mem[4] [3]),
	.B1(n_54),
	.B2(\mem[2] [3]),
	.ZN(n_73), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g3170__6131 (
	.A1(n_54),
	.A2(\mem[2] [6]),
	.B1(n_47),
	.B2(\mem[3] [6]),
	.ZN(n_72), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g3171__1881 (
	.A1(n_41),
	.A2(\mem[0] [6]),
	.B1(n_51),
	.B2(\mem[1] [6]),
	.ZN(n_71), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g3172__5115 (
	.A1(n_41),
	.A2(\mem[0] [7]),
	.B1(n_47),
	.B2(\mem[3] [7]),
	.ZN(n_70), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g3173__7482 (
	.A1(n_49),
	.A2(\mem[12] [3]),
	.B1(n_43),
	.B2(\mem[13] [3]),
	.ZN(n_69), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g3174__4733 (
	.A1(n_55),
	.A2(\mem[14] [7]),
	.B1(n_52),
	.B2(\mem[15] [7]),
	.ZN(n_68), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g3175__6161 (
	.A1(n_42),
	.A2(\mem[8] [3]),
	.B1(n_46),
	.B2(\mem[9] [3]),
	.ZN(n_67), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g3176__9315 (
	.A1(n_56),
	.A2(\mem[4] [5]),
	.B1(n_50),
	.B2(\mem[7] [5]),
	.ZN(n_66), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   aoi22d1 g3177__9945 (
	.A1(n_55),
	.A2(\mem[14] [3]),
	.B1(n_52),
	.B2(\mem[15] [3]),
	.ZN(n_65), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 g3178__2883 (
	.A1(n_43),
	.A2(\mem[13] [2]),
	.ZN(n_64), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 g3179__2346 (
	.A1(n_53),
	.A2(\mem[5] [5]),
	.ZN(n_63), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 g3180__1666 (
	.A1(n_41),
	.A2(\mem[0] [0]),
	.ZN(n_62), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 g3181__7410 (
	.A1(n_51),
	.A2(\mem[1] [1]),
	.ZN(n_61), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 g3182__6417 (
	.A1(n_53),
	.A2(\mem[5] [3]),
	.ZN(n_60), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 g3183__5477 (
	.A1(n_52),
	.A2(\mem[15] [6]),
	.ZN(n_59), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 g3184__2398 (
	.A1(n_43),
	.A2(\mem[13] [4]),
	.ZN(n_58), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 g3185__5107 (
	.A1(n_54),
	.A2(\mem[2] [7]),
	.ZN(n_57), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g3186__6260 (
	.A1(n_35),
	.A2(n_39),
	.ZN(n_56), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g3187__4319 (
	.A1(n_36),
	.A2(n_40),
	.ZN(n_55), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g3188__8428 (
	.A1(n_35),
	.A2(n_38),
	.ZN(n_54), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g3189__5526 (
	.A1(n_39),
	.A2(n_37),
	.ZN(n_53), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g3190__6783 (
	.A1(n_36),
	.A2(n_33),
	.ZN(n_52), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g3191__3680 (
	.A1(n_34),
	.A2(n_37),
	.ZN(n_51), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g3192__1617 (
	.A1(n_36),
	.A2(n_37),
	.ZN(n_50), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g3193__2802 (
	.A1(n_40),
	.A2(n_39),
	.ZN(n_49), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g3194__1705 (
	.A1(n_33),
	.A2(n_38),
	.ZN(n_48), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g3195__5122 (
	.A1(n_38),
	.A2(n_37),
	.ZN(n_47), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g3196__8246 (
	.A1(n_33),
	.A2(n_34),
	.ZN(n_46), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g3197__7098 (
	.A1(n_36),
	.A2(n_35),
	.ZN(n_45), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g3198__6131 (
	.A1(n_40),
	.A2(n_38),
	.ZN(n_44), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g3199__1881 (
	.A1(n_33),
	.A2(n_39),
	.ZN(n_43), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g3200__5115 (
	.A1(n_34),
	.A2(n_40),
	.ZN(n_42), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g3201__7482 (
	.A1(n_34),
	.A2(n_35),
	.ZN(n_41), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd12d1 g3202__4733 (
	.A1(rd_addr[0]),
	.A2(rd_addr[3]),
	.ZN(n_40), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd12d1 g3203__6161 (
	.A1(rd_addr[1]),
	.A2(rd_addr[2]),
	.ZN(n_39), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd12d1 g3204__9315 (
	.A1(rd_addr[2]),
	.A2(rd_addr[1]),
	.ZN(n_38), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd12d1 g3205__9945 (
	.A1(rd_addr[3]),
	.A2(rd_addr[0]),
	.ZN(n_37), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 g3206__2883 (
	.A1(rd_addr[2]),
	.A2(rd_addr[1]),
	.ZN(n_36), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   or02d1 g3207__2346 (
	.A1(rd_addr[0]),
	.A2(rd_addr[3]),
	.Z(n_35), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   or02d1 g3208__1666 (
	.A1(rd_addr[1]),
	.A2(rd_addr[2]),
	.Z(n_34), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 g3209__7410 (
	.A1(rd_addr[3]),
	.A2(rd_addr[0]),
	.ZN(n_33), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[0][0]  (
	.CDN(FE_OFN0_wr_rst),
	.CP(clk_clone1),
	.D(wr_data[0]),
	.ENN(n_23),
	.Q(\mem[0] [0]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[0][1]  (
	.CDN(FE_OFN0_wr_rst),
	.CP(clk_clone1),
	.D(wr_data[1]),
	.ENN(n_23),
	.Q(\mem[0] [1]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[0][2]  (
	.CDN(FE_OFN0_wr_rst),
	.CP(clk_clone1),
	.D(wr_data[2]),
	.ENN(n_23),
	.Q(\mem[0] [2]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[0][3]  (
	.CDN(FE_OFN0_wr_rst),
	.CP(CTS_1),
	.D(wr_data[3]),
	.ENN(n_23),
	.Q(\mem[0] [3]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[0][4]  (
	.CDN(rst),
	.CP(CTS_1),
	.D(wr_data[4]),
	.ENN(n_23),
	.Q(\mem[0] [4]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[0][5]  (
	.CDN(rst),
	.CP(CTS_1),
	.D(wr_data[5]),
	.ENN(n_23),
	.Q(\mem[0] [5]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[0][6]  (
	.CDN(rst),
	.CP(CTS_1),
	.D(wr_data[6]),
	.ENN(n_23),
	.Q(\mem[0] [6]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[0][7]  (
	.CDN(FE_OFN0_wr_rst),
	.CP(CTS_1),
	.D(wr_data[7]),
	.ENN(n_23),
	.Q(\mem[0] [7]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[1][0]  (
	.CDN(FE_OFN0_wr_rst),
	.CP(clk_clone1),
	.D(wr_data[0]),
	.ENN(n_31),
	.Q(\mem[1] [0]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[1][1]  (
	.CDN(FE_OFN0_wr_rst),
	.CP(clk_clone1),
	.D(wr_data[1]),
	.ENN(n_31),
	.Q(\mem[1] [1]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[1][2]  (
	.CDN(FE_OFN0_wr_rst),
	.CP(clk_clone1),
	.D(wr_data[2]),
	.ENN(n_31),
	.Q(\mem[1] [2]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[1][3]  (
	.CDN(FE_OFN0_wr_rst),
	.CP(CTS_1),
	.D(wr_data[3]),
	.ENN(n_31),
	.Q(\mem[1] [3]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[1][4]  (
	.CDN(rst),
	.CP(clk_clone1),
	.D(wr_data[4]),
	.ENN(n_31),
	.Q(\mem[1] [4]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[1][5]  (
	.CDN(rst),
	.CP(CTS_1),
	.D(wr_data[5]),
	.ENN(n_31),
	.Q(\mem[1] [5]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[1][6]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(CTS_1),
	.D(wr_data[6]),
	.ENN(n_31),
	.Q(\mem[1] [6]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[1][7]  (
	.CDN(FE_OFN0_wr_rst),
	.CP(CTS_1),
	.D(wr_data[7]),
	.ENN(n_31),
	.Q(\mem[1] [7]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[2][0]  (
	.CDN(rst),
	.CP(clk_clone1),
	.D(wr_data[0]),
	.ENN(n_26),
	.Q(\mem[2] [0]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[2][1]  (
	.CDN(rst),
	.CP(clk_clone1),
	.D(wr_data[1]),
	.ENN(n_26),
	.Q(\mem[2] [1]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[2][2]  (
	.CDN(rst),
	.CP(clk_clone1),
	.D(wr_data[2]),
	.ENN(n_26),
	.Q(\mem[2] [2]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[2][3]  (
	.CDN(FE_OFN0_wr_rst),
	.CP(clk_clone1),
	.D(wr_data[3]),
	.ENN(n_26),
	.Q(\mem[2] [3]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[2][4]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(CTS_1),
	.D(wr_data[4]),
	.ENN(n_26),
	.Q(\mem[2] [4]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[2][5]  (
	.CDN(rst),
	.CP(CTS_1),
	.D(wr_data[5]),
	.ENN(n_26),
	.Q(\mem[2] [5]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[2][6]  (
	.CDN(rst),
	.CP(CTS_1),
	.D(wr_data[6]),
	.ENN(n_26),
	.Q(\mem[2] [6]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[2][7]  (
	.CDN(rst),
	.CP(CTS_1),
	.D(wr_data[7]),
	.ENN(n_26),
	.Q(\mem[2] [7]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[3][0]  (
	.CDN(rst),
	.CP(clk_clone1),
	.D(wr_data[0]),
	.ENN(n_25),
	.Q(\mem[3] [0]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[3][1]  (
	.CDN(rst),
	.CP(clk_clone1),
	.D(wr_data[1]),
	.ENN(n_25),
	.Q(\mem[3] [1]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[3][2]  (
	.CDN(rst),
	.CP(clk_clone1),
	.D(wr_data[2]),
	.ENN(n_25),
	.Q(\mem[3] [2]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[3][3]  (
	.CDN(rst),
	.CP(CTS_1),
	.D(wr_data[3]),
	.ENN(n_25),
	.Q(\mem[3] [3]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[3][4]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(CTS_1),
	.D(wr_data[4]),
	.ENN(n_25),
	.Q(\mem[3] [4]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[3][5]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(CTS_1),
	.D(wr_data[5]),
	.ENN(n_25),
	.Q(\mem[3] [5]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[3][6]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(CTS_1),
	.D(wr_data[6]),
	.ENN(n_25),
	.Q(\mem[3] [6]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[3][7]  (
	.CDN(rst),
	.CP(CTS_1),
	.D(wr_data[7]),
	.ENN(n_25),
	.Q(\mem[3] [7]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[4][0]  (
	.CDN(FE_OFN0_wr_rst),
	.CP(clk_clone1),
	.D(wr_data[0]),
	.ENN(n_21),
	.Q(\mem[4] [0]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[4][1]  (
	.CDN(FE_OFN0_wr_rst),
	.CP(clk_clone1),
	.D(wr_data[1]),
	.ENN(n_21),
	.Q(\mem[4] [1]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[4][2]  (
	.CDN(rst),
	.CP(clk_clone1),
	.D(wr_data[2]),
	.ENN(n_21),
	.Q(\mem[4] [2]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[4][3]  (
	.CDN(FE_OFN0_wr_rst),
	.CP(CTS_1),
	.D(wr_data[3]),
	.ENN(n_21),
	.Q(\mem[4] [3]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[4][4]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(CTS_1),
	.D(wr_data[4]),
	.ENN(n_21),
	.Q(\mem[4] [4]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[4][5]  (
	.CDN(FE_OFN0_wr_rst),
	.CP(CTS_1),
	.D(wr_data[5]),
	.ENN(n_21),
	.Q(\mem[4] [5]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[4][6]  (
	.CDN(rst),
	.CP(CTS_1),
	.D(wr_data[6]),
	.ENN(n_21),
	.Q(\mem[4] [6]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[4][7]  (
	.CDN(rst),
	.CP(CTS_1),
	.D(wr_data[7]),
	.ENN(n_21),
	.Q(\mem[4] [7]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[5][0]  (
	.CDN(FE_OFN0_wr_rst),
	.CP(clk_clone1),
	.D(wr_data[0]),
	.ENN(n_18),
	.Q(\mem[5] [0]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[5][1]  (
	.CDN(FE_OFN0_wr_rst),
	.CP(clk_clone1),
	.D(wr_data[1]),
	.ENN(n_18),
	.Q(\mem[5] [1]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[5][2]  (
	.CDN(rst),
	.CP(clk_clone1),
	.D(wr_data[2]),
	.ENN(n_18),
	.Q(\mem[5] [2]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[5][3]  (
	.CDN(FE_OFN0_wr_rst),
	.CP(clk_clone1),
	.D(wr_data[3]),
	.ENN(n_18),
	.Q(\mem[5] [3]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[5][4]  (
	.CDN(rst),
	.CP(CTS_1),
	.D(wr_data[4]),
	.ENN(n_18),
	.Q(\mem[5] [4]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[5][5]  (
	.CDN(rst),
	.CP(CTS_1),
	.D(wr_data[5]),
	.ENN(n_18),
	.Q(\mem[5] [5]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[5][6]  (
	.CDN(rst),
	.CP(CTS_1),
	.D(wr_data[6]),
	.ENN(n_18),
	.Q(\mem[5] [6]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[5][7]  (
	.CDN(rst),
	.CP(CTS_1),
	.D(wr_data[7]),
	.ENN(n_18),
	.Q(\mem[5] [7]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[6][0]  (
	.CDN(FE_OFN0_wr_rst),
	.CP(clk_clone1),
	.D(wr_data[0]),
	.ENN(n_30),
	.Q(\mem[6] [0]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[6][1]  (
	.CDN(FE_OFN0_wr_rst),
	.CP(clk_clone1),
	.D(wr_data[1]),
	.ENN(n_30),
	.Q(\mem[6] [1]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[6][2]  (
	.CDN(rst),
	.CP(clk_clone1),
	.D(wr_data[2]),
	.ENN(n_30),
	.Q(\mem[6] [2]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[6][3]  (
	.CDN(rst),
	.CP(CTS_1),
	.D(wr_data[3]),
	.ENN(n_30),
	.Q(\mem[6] [3]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[6][4]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(CTS_1),
	.D(wr_data[4]),
	.ENN(n_30),
	.Q(\mem[6] [4]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[6][5]  (
	.CDN(rst),
	.CP(CTS_1),
	.D(wr_data[5]),
	.ENN(n_30),
	.Q(\mem[6] [5]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[6][6]  (
	.CDN(rst),
	.CP(CTS_1),
	.D(wr_data[6]),
	.ENN(n_30),
	.Q(\mem[6] [6]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[6][7]  (
	.CDN(FE_OFN0_wr_rst),
	.CP(CTS_1),
	.D(wr_data[7]),
	.ENN(n_30),
	.Q(\mem[6] [7]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[7][0]  (
	.CDN(FE_OFN0_wr_rst),
	.CP(clk_clone1),
	.D(wr_data[0]),
	.ENN(n_29),
	.Q(\mem[7] [0]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[7][1]  (
	.CDN(FE_OFN0_wr_rst),
	.CP(clk_clone1),
	.D(wr_data[1]),
	.ENN(n_29),
	.Q(\mem[7] [1]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[7][2]  (
	.CDN(rst),
	.CP(clk_clone1),
	.D(wr_data[2]),
	.ENN(n_29),
	.Q(\mem[7] [2]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[7][3]  (
	.CDN(rst),
	.CP(clk_clone1),
	.D(wr_data[3]),
	.ENN(n_29),
	.Q(\mem[7] [3]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[7][4]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(CTS_1),
	.D(wr_data[4]),
	.ENN(n_29),
	.Q(\mem[7] [4]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[7][5]  (
	.CDN(FE_OFN0_wr_rst),
	.CP(CTS_1),
	.D(wr_data[5]),
	.ENN(n_29),
	.Q(\mem[7] [5]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[7][6]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(CTS_1),
	.D(wr_data[6]),
	.ENN(n_29),
	.Q(\mem[7] [6]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[7][7]  (
	.CDN(FE_OFN0_wr_rst),
	.CP(CTS_1),
	.D(wr_data[7]),
	.ENN(n_29),
	.Q(\mem[7] [7]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[8][0]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(clk_clone1),
	.D(wr_data[0]),
	.ENN(n_32),
	.Q(\mem[8] [0]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[8][1]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(clk_clone1),
	.D(wr_data[1]),
	.ENN(n_32),
	.Q(\mem[8] [1]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[8][2]  (
	.CDN(rst),
	.CP(clk_clone1),
	.D(wr_data[2]),
	.ENN(n_32),
	.Q(\mem[8] [2]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[8][3]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(CTS_1),
	.D(wr_data[3]),
	.ENN(n_32),
	.Q(\mem[8] [3]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[8][4]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(CTS_1),
	.D(wr_data[4]),
	.ENN(n_32),
	.Q(\mem[8] [4]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[8][5]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(CTS_1),
	.D(wr_data[5]),
	.ENN(n_32),
	.Q(\mem[8] [5]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[8][6]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(CTS_1),
	.D(wr_data[6]),
	.ENN(n_32),
	.Q(\mem[8] [6]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[8][7]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(CTS_1),
	.D(wr_data[7]),
	.ENN(n_32),
	.Q(\mem[8] [7]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[9][0]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(clk_clone1),
	.D(wr_data[0]),
	.ENN(n_20),
	.Q(\mem[9] [0]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[9][1]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(clk_clone1),
	.D(wr_data[1]),
	.ENN(n_20),
	.Q(\mem[9] [1]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[9][2]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(clk_clone1),
	.D(wr_data[2]),
	.ENN(n_20),
	.Q(\mem[9] [2]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[9][3]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(CTS_1),
	.D(wr_data[3]),
	.ENN(n_20),
	.Q(\mem[9] [3]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[9][4]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(CTS_1),
	.D(wr_data[4]),
	.ENN(n_20),
	.Q(\mem[9] [4]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[9][5]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(CTS_1),
	.D(wr_data[5]),
	.ENN(n_20),
	.Q(\mem[9] [5]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[9][6]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(CTS_1),
	.D(wr_data[6]),
	.ENN(n_20),
	.Q(\mem[9] [6]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[9][7]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(CTS_1),
	.D(wr_data[7]),
	.ENN(n_20),
	.Q(\mem[9] [7]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[10][0]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(clk_clone1),
	.D(wr_data[0]),
	.ENN(n_17),
	.Q(\mem[10] [0]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[10][1]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(clk_clone1),
	.D(wr_data[1]),
	.ENN(n_17),
	.Q(\mem[10] [1]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[10][2]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(clk_clone1),
	.D(wr_data[2]),
	.ENN(n_17),
	.Q(\mem[10] [2]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[10][3]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(clk_clone1),
	.D(wr_data[3]),
	.ENN(n_17),
	.Q(\mem[10] [3]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[10][4]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(CTS_1),
	.D(wr_data[4]),
	.ENN(n_17),
	.Q(\mem[10] [4]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[10][5]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(CTS_1),
	.D(wr_data[5]),
	.ENN(n_17),
	.Q(\mem[10] [5]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[10][6]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(CTS_1),
	.D(wr_data[6]),
	.ENN(n_17),
	.Q(\mem[10] [6]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[10][7]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(CTS_1),
	.D(wr_data[7]),
	.ENN(n_17),
	.Q(\mem[10] [7]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[11][0]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(clk_clone1),
	.D(wr_data[0]),
	.ENN(n_22),
	.Q(\mem[11] [0]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[11][1]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(clk_clone1),
	.D(wr_data[1]),
	.ENN(n_22),
	.Q(\mem[11] [1]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[11][2]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(clk_clone1),
	.D(wr_data[2]),
	.ENN(n_22),
	.Q(\mem[11] [2]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[11][3]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(CTS_1),
	.D(wr_data[3]),
	.ENN(n_22),
	.Q(\mem[11] [3]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[11][4]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(CTS_1),
	.D(wr_data[4]),
	.ENN(n_22),
	.Q(\mem[11] [4]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[11][5]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(CTS_1),
	.D(wr_data[5]),
	.ENN(n_22),
	.Q(\mem[11] [5]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[11][6]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(CTS_1),
	.D(wr_data[6]),
	.ENN(n_22),
	.Q(\mem[11] [6]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[11][7]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(CTS_1),
	.D(wr_data[7]),
	.ENN(n_22),
	.Q(\mem[11] [7]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[12][0]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(clk_clone1),
	.D(wr_data[0]),
	.ENN(n_28),
	.Q(\mem[12] [0]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[12][1]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(clk_clone1),
	.D(wr_data[1]),
	.ENN(n_28),
	.Q(\mem[12] [1]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[12][2]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(CTS_1),
	.D(wr_data[2]),
	.ENN(n_28),
	.Q(\mem[12] [2]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[12][3]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(CTS_1),
	.D(wr_data[3]),
	.ENN(n_28),
	.Q(\mem[12] [3]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[12][4]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(CTS_1),
	.D(wr_data[4]),
	.ENN(n_28),
	.Q(\mem[12] [4]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[12][5]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(CTS_1),
	.D(wr_data[5]),
	.ENN(n_28),
	.Q(\mem[12] [5]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[12][6]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(CTS_1),
	.D(wr_data[6]),
	.ENN(n_28),
	.Q(\mem[12] [6]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[12][7]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(CTS_1),
	.D(wr_data[7]),
	.ENN(n_28),
	.Q(\mem[12] [7]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[13][0]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(clk_clone1),
	.D(wr_data[0]),
	.ENN(n_27),
	.Q(\mem[13] [0]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[13][1]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(clk_clone1),
	.D(wr_data[1]),
	.ENN(n_27),
	.Q(\mem[13] [1]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[13][2]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(clk_clone1),
	.D(wr_data[2]),
	.ENN(n_27),
	.Q(\mem[13] [2]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[13][3]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(clk_clone1),
	.D(wr_data[3]),
	.ENN(n_27),
	.Q(\mem[13] [3]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[13][4]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(CTS_1),
	.D(wr_data[4]),
	.ENN(n_27),
	.Q(\mem[13] [4]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[13][5]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(CTS_1),
	.D(wr_data[5]),
	.ENN(n_27),
	.Q(\mem[13] [5]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[13][6]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(CTS_1),
	.D(wr_data[6]),
	.ENN(n_27),
	.Q(\mem[13] [6]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[13][7]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(CTS_1),
	.D(wr_data[7]),
	.ENN(n_27),
	.Q(\mem[13] [7]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[14][0]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(clk_clone1),
	.D(wr_data[0]),
	.ENN(n_19),
	.Q(\mem[14] [0]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[14][1]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(clk_clone1),
	.D(wr_data[1]),
	.ENN(n_19),
	.Q(\mem[14] [1]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[14][2]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(clk_clone1),
	.D(wr_data[2]),
	.ENN(n_19),
	.Q(\mem[14] [2]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[14][3]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(CTS_1),
	.D(wr_data[3]),
	.ENN(n_19),
	.Q(\mem[14] [3]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[14][4]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(CTS_1),
	.D(wr_data[4]),
	.ENN(n_19),
	.Q(\mem[14] [4]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[14][5]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(CTS_1),
	.D(wr_data[5]),
	.ENN(n_19),
	.Q(\mem[14] [5]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[14][6]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(CTS_1),
	.D(wr_data[6]),
	.ENN(n_19),
	.Q(\mem[14] [6]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[14][7]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(CTS_1),
	.D(wr_data[7]),
	.ENN(n_19),
	.Q(\mem[14] [7]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[15][0]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(clk_clone1),
	.D(wr_data[0]),
	.ENN(n_24),
	.Q(\mem[15] [0]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[15][1]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(clk_clone1),
	.D(wr_data[1]),
	.ENN(n_24),
	.Q(\mem[15] [1]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[15][2]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(CTS_1),
	.D(wr_data[2]),
	.ENN(n_24),
	.Q(\mem[15] [2]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[15][3]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(CTS_1),
	.D(wr_data[3]),
	.ENN(n_24),
	.Q(\mem[15] [3]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[15][4]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(CTS_1),
	.D(wr_data[4]),
	.ENN(n_24),
	.Q(\mem[15] [4]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[15][5]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(CTS_1),
	.D(wr_data[5]),
	.ENN(n_24),
	.Q(\mem[15] [5]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[15][6]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(CTS_1),
	.D(wr_data[6]),
	.ENN(n_24),
	.Q(\mem[15] [6]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   decrq1 \mem_reg[15][7]  (
	.CDN(FE_OFN11_wr_rst),
	.CP(CTS_1),
	.D(wr_data[7]),
	.ENN(n_24),
	.Q(\mem[15] [7]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   or02d1 g1967__6417 (
	.A1(n_1),
	.A2(wr_addr[0]),
	.Z(n_32), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 g1968__5477 (
	.A1(n_13),
	.A2(FE_PHN15_wr_addr_0),
	.ZN(n_31), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 g1969__2398 (
	.A1(n_14),
	.A2(n_2),
	.ZN(n_30), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 g1970__5107 (
	.A1(n_14),
	.A2(FE_PHN21_wr_addr_0),
	.ZN(n_29), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   or02d1 g1971__6260 (
	.A1(n_16),
	.A2(wr_addr[0]),
	.Z(n_28), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd12d1 g1972__4319 (
	.A1(n_16),
	.A2(wr_addr[0]),
	.ZN(n_27), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 g1973__8428 (
	.A1(n_12),
	.A2(n_2),
	.ZN(n_26), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 g1974__5526 (
	.A1(n_12),
	.A2(FE_PHN15_wr_addr_0),
	.ZN(n_25), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 g1975__6783 (
	.A1(n_11),
	.A2(FE_PHN15_wr_addr_0),
	.ZN(n_24), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 g1976__3680 (
	.A1(n_13),
	.A2(n_2),
	.ZN(n_23), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 g1977__1617 (
	.A1(n_15),
	.A2(wr_addr[0]),
	.ZN(n_22), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 g1978__2802 (
	.A1(n_0),
	.A2(n_2),
	.ZN(n_21), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd12d1 g1979__1705 (
	.A1(n_1),
	.A2(wr_addr[0]),
	.ZN(n_20), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 g1980__5122 (
	.A1(n_11),
	.A2(n_2),
	.ZN(n_19), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 g1981__8246 (
	.A1(n_0),
	.A2(wr_addr[0]),
	.ZN(n_18), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 g1982__7098 (
	.A1(n_15),
	.A2(n_2),
	.ZN(n_17), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 g1984__6131 (
	.A1(n_8),
	.A2(wr_addr[3]),
	.ZN(n_16), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g1985__1881 (
	.A1(n_3),
	.A2(n_7),
	.ZN(n_15), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g1986__5115 (
	.A1(wr_addr[3]),
	.A2(n_10),
	.ZN(n_14), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g1987__7482 (
	.A1(wr_addr[3]),
	.A2(n_9),
	.ZN(n_13), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g1988__4733 (
	.A1(wr_addr[3]),
	.A2(n_7),
	.ZN(n_12), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g1989__6161 (
	.A1(n_3),
	.A2(n_10),
	.ZN(n_11), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd12d1 g1992__9315 (
	.A1(n_6),
	.A2(wr_addr[1]),
	.ZN(n_10), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd12d1 g1993__9945 (
	.A1(wr_addr[1]),
	.A2(n_5),
	.ZN(n_9), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g1995__2883 (
	.A1(wr_addr[1]),
	.A2(n_6),
	.ZN(n_8), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd02d1 g1996__2346 (
	.A1(n_5),
	.A2(wr_addr[1]),
	.ZN(n_7), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd12d1 g1997__1666 (
	.A1(n_4),
	.A2(wr_addr[2]),
	.ZN(n_6), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nr02d1 g1998__7410 (
	.A1(wr_addr[2]),
	.A2(n_4),
	.ZN(n_5), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd12d1 g1999__6417 (
	.A1(full),
	.A2(wr_en),
	.ZN(n_4), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   inv0d0 g2000 (
	.I(wr_addr[3]),
	.ZN(n_3), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   inv0d0 g2001 (
	.I(wr_addr[0]),
	.ZN(n_2), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   nd12d1 g2__5477 (
	.A1(n_9),
	.A2(wr_addr[3]),
	.ZN(n_1), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   an12d1 g2002__2398 (
	.A1(wr_addr[3]),
	.A2(n_8),
	.Z(n_0), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
endmodule

module dff_37 (
	clk, 
	rst, 
	wr_data, 
	rd_data, 
	VDD_CORE, 
	VSS_CORE);
   input clk;
   input rst;
   input [4:0] wr_data;
   output [4:0] rd_data;
   inout VDD_CORE;
   inout VSS_CORE;

   // Module instantiations
   dfcrq1 \rd_data_reg[4]  (
	.CDN(rst),
	.CP(clk),
	.D(wr_data[4]),
	.Q(rd_data[4]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \rd_data_reg[3]  (
	.CDN(rst),
	.CP(clk),
	.D(wr_data[3]),
	.Q(rd_data[3]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \rd_data_reg[1]  (
	.CDN(rst),
	.CP(clk),
	.D(wr_data[1]),
	.Q(rd_data[1]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \rd_data_reg[0]  (
	.CDN(rst),
	.CP(clk),
	.D(wr_data[0]),
	.Q(rd_data[0]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \rd_data_reg[2]  (
	.CDN(rst),
	.CP(clk),
	.D(wr_data[2]),
	.Q(rd_data[2]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
endmodule

module dff_36 (
	clk, 
	rst, 
	wr_data, 
	rd_data, 
	VDD_CORE, 
	VSS_CORE);
   input clk;
   input rst;
   input [4:0] wr_data;
   output [4:0] rd_data;
   inout VDD_CORE;
   inout VSS_CORE;

   // Internal wires
   wire FE_PHN9_in_data_n_1;
   wire FE_PHN8_in_data_n_3;
   wire FE_PHN7_in_data_n_2;
   wire FE_PHN6_in_data_n_0;
   wire FE_PHN5_in_data_n_4;

   // Module instantiations
   dl03d1 FE_PHC9_in_data_n_1 (
	.I(wr_data[1]),
	.Z(FE_PHN9_in_data_n_1), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dl03d1 FE_PHC8_in_data_n_3 (
	.I(wr_data[3]),
	.Z(FE_PHN8_in_data_n_3), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dl03d1 FE_PHC7_in_data_n_2 (
	.I(wr_data[2]),
	.Z(FE_PHN7_in_data_n_2), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dl03d1 FE_PHC6_in_data_n_0 (
	.I(wr_data[0]),
	.Z(FE_PHN6_in_data_n_0), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dl03d1 FE_PHC5_in_data_n_4 (
	.I(wr_data[4]),
	.Z(FE_PHN5_in_data_n_4), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \rd_data_reg[4]  (
	.CDN(rst),
	.CP(clk),
	.D(FE_PHN5_in_data_n_4),
	.Q(rd_data[4]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \rd_data_reg[3]  (
	.CDN(rst),
	.CP(clk),
	.D(FE_PHN8_in_data_n_3),
	.Q(rd_data[3]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \rd_data_reg[1]  (
	.CDN(rst),
	.CP(clk),
	.D(FE_PHN9_in_data_n_1),
	.Q(rd_data[1]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \rd_data_reg[0]  (
	.CDN(rst),
	.CP(clk),
	.D(FE_PHN6_in_data_n_0),
	.Q(rd_data[0]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \rd_data_reg[2]  (
	.CDN(rst),
	.CP(clk),
	.D(FE_PHN7_in_data_n_2),
	.Q(rd_data[2]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
endmodule

module cdc_synchronizer_35 (
	clk, 
	rst, 
	in_data, 
	out_data, 
	VDD_CORE, 
	VSS_CORE);
   input clk;
   input rst;
   input [4:0] in_data;
   output [4:0] out_data;
   inout VDD_CORE;
   inout VSS_CORE;

   // Internal wires
   wire [4:0] in_data_n;

   // Module instantiations
   dff_37 dff_1 (
	.clk(clk),
	.rst(rst),
	.wr_data(in_data),
	.rd_data(in_data_n), 
	.VDD_CORE(VDD_CORE), 
	.VSS_CORE(VSS_CORE));
   dff_36 dff_2 (
	.clk(clk),
	.rst(rst),
	.wr_data(in_data_n),
	.rd_data(out_data), 
	.VDD_CORE(VDD_CORE), 
	.VSS_CORE(VSS_CORE));
endmodule

module dff (
	rst, 
	wr_data, 
	rd_data, 
	clk, 
	VDD_CORE, 
	VSS_CORE);
   input rst;
   input [4:0] wr_data;
   output [4:0] rd_data;
   input clk;
   inout VDD_CORE;
   inout VSS_CORE;

   // Module instantiations
   dfcrq1 \rd_data_reg[4]  (
	.CDN(rst),
	.CP(clk),
	.D(wr_data[4]),
	.Q(rd_data[4]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \rd_data_reg[3]  (
	.CDN(rst),
	.CP(clk),
	.D(wr_data[3]),
	.Q(rd_data[3]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \rd_data_reg[1]  (
	.CDN(rst),
	.CP(clk),
	.D(wr_data[1]),
	.Q(rd_data[1]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \rd_data_reg[2]  (
	.CDN(rst),
	.CP(clk),
	.D(wr_data[2]),
	.Q(rd_data[2]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \rd_data_reg[0]  (
	.CDN(rst),
	.CP(clk),
	.D(wr_data[0]),
	.Q(rd_data[0]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
endmodule

module dff_38 (
	rst, 
	wr_data, 
	rd_data, 
	clk, 
	VDD_CORE, 
	VSS_CORE);
   input rst;
   input [4:0] wr_data;
   output [4:0] rd_data;
   input clk;
   inout VDD_CORE;
   inout VSS_CORE;

   // Internal wires
   wire FE_PHN14_in_data_n_2;
   wire FE_PHN13_in_data_n_0;
   wire FE_PHN12_in_data_n_1;
   wire FE_PHN11_in_data_n_4;
   wire FE_PHN10_in_data_n_3;

   // Module instantiations
   dl01d1 FE_PHC14_in_data_n_2 (
	.I(wr_data[2]),
	.Z(FE_PHN14_in_data_n_2), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dl01d1 FE_PHC13_in_data_n_0 (
	.I(wr_data[0]),
	.Z(FE_PHN13_in_data_n_0), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dl01d1 FE_PHC12_in_data_n_1 (
	.I(wr_data[1]),
	.Z(FE_PHN12_in_data_n_1), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dl01d1 FE_PHC11_in_data_n_4 (
	.I(wr_data[4]),
	.Z(FE_PHN11_in_data_n_4), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dl01d1 FE_PHC10_in_data_n_3 (
	.I(wr_data[3]),
	.Z(FE_PHN10_in_data_n_3), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \rd_data_reg[4]  (
	.CDN(rst),
	.CP(clk),
	.D(FE_PHN11_in_data_n_4),
	.Q(rd_data[4]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \rd_data_reg[3]  (
	.CDN(rst),
	.CP(clk),
	.D(FE_PHN10_in_data_n_3),
	.Q(rd_data[3]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \rd_data_reg[1]  (
	.CDN(rst),
	.CP(clk),
	.D(FE_PHN12_in_data_n_1),
	.Q(rd_data[1]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \rd_data_reg[0]  (
	.CDN(rst),
	.CP(clk),
	.D(FE_PHN13_in_data_n_0),
	.Q(rd_data[0]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   dfcrq1 \rd_data_reg[2]  (
	.CDN(rst),
	.CP(clk),
	.D(FE_PHN14_in_data_n_2),
	.Q(rd_data[2]), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
endmodule

module cdc_synchronizer (
	rst, 
	in_data, 
	out_data, 
	clk, 
	VDD_CORE, 
	VSS_CORE);
   input rst;
   input [4:0] in_data;
   output [4:0] out_data;
   input clk;
   inout VDD_CORE;
   inout VSS_CORE;

   // Internal wires
   wire [4:0] in_data_n;

   // Module instantiations
   dff dff_1 (
	.rst(rst),
	.wr_data(in_data),
	.rd_data(in_data_n),
	.clk(clk), 
	.VDD_CORE(VDD_CORE), 
	.VSS_CORE(VSS_CORE));
   dff_38 dff_2 (
	.rst(rst),
	.wr_data(in_data_n),
	.rd_data(out_data),
	.clk(clk), 
	.VDD_CORE(VDD_CORE), 
	.VSS_CORE(VSS_CORE));
endmodule

module fifo_top (
	wr_clk_pad, 
	rd_clk_pad, 
	wr_en_pad, 
	rd_en_pad, 
	wr_rst_pad, 
	rd_rst_pad, 
	wr_data_pad, 
	rd_data_pad, 
	empty_pad, 
	full_pad);
   input wr_clk_pad;
   input rd_clk_pad;
   input wr_en_pad;
   input rd_en_pad;
   input wr_rst_pad;
   input rd_rst_pad;
   input [7:0] wr_data_pad;
   output [7:0] rd_data_pad;
   output empty_pad;
   output full_pad;

   // Internal wires
   wire CTS_1;
   wire FE_OFN10_wr_rst;
   wire FE_OFN7_rd_data_0;
   wire FE_OFN6_rd_data_1;
   wire FE_OFN5_rd_data_2;
   wire FE_OFN4_rd_data_3;
   wire FE_OFN3_rd_data_4;
   wire FE_OFN2_rd_data_5;
   wire FE_OFN1_rd_data_6;
   wire FE_OFN0_rd_data_7;
   wire [4:0] wr_addr_grey_sync;
   wire [4:0] rd_addr_grey;
   wire [3:0] rd_addr;
   wire [4:0] rd_addr_grey_sync;
   wire [4:0] wr_addr_grey;
   wire [3:0] wr_addr;
   wire [7:0] wr_data;
   wire [7:0] rd_data;
   wire empty;
   wire full;
   wire rd_clk;
   wire rd_en;
   wire rd_rst;
   wire read_clk;
   wire wr_clk;
   wire wr_en;
   wire wr_rst;
   wire write_clk;
   wire VDD_CORE;
   wire VSS_CORE;
   wire VDDO_CORE;
   wire VSSO_CORE;

   // Module instantiations
   bufbd7 CTS_ccl_a_buf_00061 (
	.I(wr_clk),
	.Z(CTS_1), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   buffd3 FE_OFC10_wr_rst (
	.I(wr_rst),
	.Z(FE_OFN10_wr_rst), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   buffd3 FE_OFC7_rd_data_0 (
	.I(rd_data[0]),
	.Z(FE_OFN7_rd_data_0), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   buffd3 FE_OFC6_rd_data_1 (
	.I(rd_data[1]),
	.Z(FE_OFN6_rd_data_1), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   buffd3 FE_OFC5_rd_data_2 (
	.I(rd_data[2]),
	.Z(FE_OFN5_rd_data_2), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   buffd3 FE_OFC4_rd_data_3 (
	.I(rd_data[3]),
	.Z(FE_OFN4_rd_data_3), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   buffd3 FE_OFC3_rd_data_4 (
	.I(rd_data[4]),
	.Z(FE_OFN3_rd_data_4), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   buffd3 FE_OFC2_rd_data_5 (
	.I(rd_data[5]),
	.Z(FE_OFN2_rd_data_5), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   buffd3 FE_OFC1_rd_data_6 (
	.I(rd_data[6]),
	.Z(FE_OFN1_rd_data_6), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   buffd3 FE_OFC0_rd_data_7 (
	.I(rd_data[7]),
	.Z(FE_OFN0_rd_data_7), 
	.VSS(VSS_CORE), 
	.VDD(VDD_CORE));
   fifo_empty e (
	.rd_clk(rd_clk),
	.rd_en(rd_en),
	.rd_rst(rd_rst),
	.wr_ptr_addr_sync(wr_addr_grey_sync),
	.empty(empty),
	.rd_addr_grey(rd_addr_grey),
	.rd_addr_bin(rd_addr), 
	.VDD_CORE(VDD_CORE), 
	.VSS_CORE(VSS_CORE));
   fifo_full f (
	.wr_en(wr_en),
	.wr_rst(FE_OFN10_wr_rst),
	.rd_ptr_addr_sync(rd_addr_grey_sync),
	.full(full),
	.wr_addr_grey(wr_addr_grey),
	.wr_addr_bin(wr_addr),
	.wr_clk(CTS_1), 
	.VDD_CORE(VDD_CORE), 
	.VSS_CORE(VSS_CORE));
   fifo_memory m (
	.rst(wr_rst),
	.wr_en(wr_en),
	.full(full),
	.wr_addr(wr_addr),
	.rd_addr(rd_addr),
	.wr_data(wr_data),
	.rd_data(rd_data),
	.FE_OFN0_wr_rst(FE_OFN10_wr_rst),
	.clk_clone1(CTS_1),
	.clk(wr_clk), 
	.VDD_CORE(VDD_CORE), 
	.VSS_CORE(VSS_CORE));
   cdc_synchronizer_35 rd_addr_sync (
	.clk(rd_clk),
	.rst(rd_rst),
	.in_data(wr_addr_grey),
	.out_data(wr_addr_grey_sync), 
	.VDD_CORE(VDD_CORE), 
	.VSS_CORE(VSS_CORE));
   cdc_synchronizer wr_addr_sync (
	.rst(FE_OFN10_wr_rst),
	.in_data(rd_addr_grey),
	.out_data(rd_addr_grey_sync),
	.clk(CTS_1), 
	.VDD_CORE(VDD_CORE), 
	.VSS_CORE(VSS_CORE));
   pc3c01 pc3c01_1 (
	.CCLK(read_clk),
	.CP(rd_clk), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3c01 pc3c01_2 (
	.CCLK(write_clk),
	.CP(wr_clk), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3d01 pc3d01_1 (
	.PAD(rd_clk_pad),
	.CIN(read_clk), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3d01 pc3d01_2 (
	.PAD(wr_clk_pad),
	.CIN(write_clk), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3d01 pc3d01_3 (
	.PAD(wr_rst_pad),
	.CIN(wr_rst), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3d01 pc3d01_4 (
	.PAD(rd_rst_pad),
	.CIN(rd_rst), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3d01 pc3d01_5 (
	.PAD(wr_en_pad),
	.CIN(wr_en), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3d01 pc3d01_6 (
	.PAD(rd_en_pad),
	.CIN(rd_en), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3d01 pc3d01_7 (
	.PAD(wr_data_pad[7]),
	.CIN(wr_data[7]), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3d01 pc3d01_8 (
	.PAD(wr_data_pad[6]),
	.CIN(wr_data[6]), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3d01 pc3d01_9 (
	.PAD(wr_data_pad[5]),
	.CIN(wr_data[5]), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3d01 pc3d01_10 (
	.PAD(wr_data_pad[4]),
	.CIN(wr_data[4]), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3d01 pc3d01_11 (
	.PAD(wr_data_pad[3]),
	.CIN(wr_data[3]), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3d01 pc3d01_12 (
	.PAD(wr_data_pad[2]),
	.CIN(wr_data[2]), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3d01 pc3d01_13 (
	.PAD(wr_data_pad[1]),
	.CIN(wr_data[1]), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3d01 pc3d01_14 (
	.PAD(wr_data_pad[0]),
	.CIN(wr_data[0]), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3o05 pc3o05_1 (
	.I(FE_OFN0_rd_data_7),
	.PAD(rd_data_pad[7]), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3o05 pc3o05_2 (
	.I(FE_OFN1_rd_data_6),
	.PAD(rd_data_pad[6]), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3o05 pc3o05_3 (
	.I(FE_OFN2_rd_data_5),
	.PAD(rd_data_pad[5]), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3o05 pc3o05_4 (
	.I(FE_OFN3_rd_data_4),
	.PAD(rd_data_pad[4]), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3o05 pc3o05_5 (
	.I(FE_OFN4_rd_data_3),
	.PAD(rd_data_pad[3]), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3o05 pc3o05_6 (
	.I(FE_OFN5_rd_data_2),
	.PAD(rd_data_pad[2]), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3o05 pc3o05_7 (
	.I(FE_OFN6_rd_data_1),
	.PAD(rd_data_pad[1]), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3o05 pc3o05_8 (
	.I(FE_OFN7_rd_data_0),
	.PAD(rd_data_pad[0]), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3o05 pc3o05_9 (
	.I(full),
	.PAD(full_pad), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pc3o05 pc3o05_10 (
	.I(empty),
	.PAD(empty_pad), 
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pvdi pvdi_VDD_CORE_1 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pv0i pv0i_VSS_CORE_1 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pvda pvda_VDDO_CORE_1 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pv0a pv0a_VSSO_CORE_1 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pvdi pvdi_VDD_CORE_2 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pv0i pv0i_VSS_CORE_2 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pvda pvda_VDDO_CORE_2 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pv0a pv0a_VSSO_CORE_2 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pvdi pvdi_VDD_CORE_3 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pv0i pv0i_VSS_CORE_3 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pvda pvda_VDDO_CORE_3 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pv0a pv0a_VSSO_CORE_3 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pvdi pvdi_VDD_CORE_4 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pv0i pv0i_VSS_CORE_4 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pvda pvda_VDDO_CORE_4 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pv0a pv0a_VSSO_CORE_4 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pvdi pvdi_VDD_CORE_5 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pv0i pv0i_VSS_CORE_5 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pvda pvda_VDDO_CORE_5 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
   pv0a pv0a_VSSO_CORE_5 (
	.VSSO(VSSO_CORE), 
	.VSS(VSS_CORE), 
	.VDDO(VDDO_CORE), 
	.VDD(VDD_CORE));
endmodule

