
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Feb 20 2025 10:59:09 IST (Feb 20 2025 05:29:09 UTC)

// Verification Directory fv/fifo_top 

module fifo_empty(rd_clk, rd_en, rd_rst, wr_ptr_addr_sync, empty,
     rd_addr_grey, rd_addr_bin);
  input rd_clk, rd_en, rd_rst;
  input [4:0] wr_ptr_addr_sync;
  output empty;
  output [4:0] rd_addr_grey;
  output [3:0] rd_addr_bin;
  wire rd_clk, rd_en, rd_rst;
  wire [4:0] wr_ptr_addr_sync;
  wire empty;
  wire [4:0] rd_addr_grey;
  wire [3:0] rd_addr_bin;
  wire [4:0] rd_addr_grey_next;
  wire [4:0] rd_addr_bin_next;
  wire UNCONNECTED, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17;
  inv0d0 g137(.I (rd_en), .ZN (n_17));
  dfcrq1 \rd_addr_grey_reg[3] (.CDN (rd_rst), .CP (rd_clk), .D
       (rd_addr_grey_next[3]), .Q (rd_addr_grey[3]));
  mx02d1 g184__2398(.I0 (rd_addr_bin_next[4]), .I1 (n_16), .S
       (rd_addr_bin_next[3]), .Z (rd_addr_grey_next[3]));
  dfcrq1 \rd_addr_grey_reg[2] (.CDN (rd_rst), .CP (rd_clk), .D
       (rd_addr_grey_next[2]), .Q (rd_addr_grey[2]));
  inv0d0 g186(.I (n_16), .ZN (rd_addr_bin_next[4]));
  aoim22d1 g187__5107(.A1 (n_15), .A2 (n_10), .B1 (n_15), .B2 (n_10),
       .Z (n_16));
  xr02d1 g188__6260(.A1 (rd_addr_bin_next[3]), .A2
       (rd_addr_bin_next[2]), .Z (rd_addr_grey_next[2]));
  ah01d1 g189__4319(.A (n_14), .B (rd_addr_bin[3]), .CO (n_15), .S
       (rd_addr_bin_next[3]));
  dfcrq1 \rd_addr_grey_reg[1] (.CDN (rd_rst), .CP (rd_clk), .D
       (rd_addr_grey_next[1]), .Q (rd_addr_grey[1]));
  xr02d1 g191__8428(.A1 (rd_addr_bin_next[2]), .A2
       (rd_addr_bin_next[1]), .Z (rd_addr_grey_next[1]));
  ah01d1 g192__5526(.A (n_13), .B (rd_addr_bin[2]), .CO (n_14), .S
       (rd_addr_bin_next[2]));
  dfcrq1 \rd_addr_grey_reg[0] (.CDN (rd_rst), .CP (rd_clk), .D
       (rd_addr_grey_next[0]), .Q (rd_addr_grey[0]));
  xr02d1 g194__6783(.A1 (rd_addr_bin_next[1]), .A2
       (rd_addr_bin_next[0]), .Z (rd_addr_grey_next[0]));
  ah01d1 g195__3680(.A (n_12), .B (rd_addr_bin[1]), .CO (n_13), .S
       (rd_addr_bin_next[1]));
  ah01d1 g196__1617(.A (n_11), .B (rd_addr_bin[0]), .CO (n_12), .S
       (rd_addr_bin_next[0]));
  nr02d1 g197__2802(.A1 (empty), .A2 (n_17), .ZN (n_11));
  dfprb1 empty_r_reg(.SDN (rd_rst), .CP (rd_clk), .D (n_9), .Q (empty),
       .QN (UNCONNECTED));
  oan211d1 g199__1705(.A (n_8), .B (n_3), .C1 (rd_addr_bin_next[4]),
       .C2 (wr_ptr_addr_sync[4]), .ZN (n_9));
  nd04d1 g200__5122(.A1 (n_5), .A2 (n_7), .A3 (n_4), .A4 (n_6), .ZN
       (n_8));
  oaim22d1 g201__8246(.A1 (rd_addr_grey_next[3]), .A2
       (wr_ptr_addr_sync[3]), .B1 (rd_addr_grey_next[3]), .B2
       (wr_ptr_addr_sync[3]), .ZN (n_7));
  aoim22d1 g202__7098(.A1 (rd_addr_grey_next[0]), .A2 (n_1), .B1
       (rd_addr_grey_next[0]), .B2 (n_1), .Z (n_6));
  aoim22d1 g203__6131(.A1 (rd_addr_grey_next[1]), .A2 (n_2), .B1
       (rd_addr_grey_next[1]), .B2 (n_2), .Z (n_5));
  aoim22d1 g204__1881(.A1 (rd_addr_grey_next[2]), .A2 (n_0), .B1
       (rd_addr_grey_next[2]), .B2 (n_0), .Z (n_4));
  dfcrq1 \rd_addr_bin_r_reg[0] (.CDN (rd_rst), .CP (rd_clk), .D
       (rd_addr_bin_next[0]), .Q (rd_addr_bin[0]));
  dfcrq1 \rd_addr_bin_r_reg[1] (.CDN (rd_rst), .CP (rd_clk), .D
       (rd_addr_bin_next[1]), .Q (rd_addr_bin[1]));
  dfcrq1 \rd_addr_bin_r_reg[2] (.CDN (rd_rst), .CP (rd_clk), .D
       (rd_addr_bin_next[2]), .Q (rd_addr_bin[2]));
  dfcrq1 \rd_addr_bin_r_reg[3] (.CDN (rd_rst), .CP (rd_clk), .D
       (rd_addr_bin_next[3]), .Q (rd_addr_bin[3]));
  nd02d1 g208__5115(.A1 (rd_addr_bin_next[4]), .A2
       (wr_ptr_addr_sync[4]), .ZN (n_3));
  inv0d0 g209(.I (wr_ptr_addr_sync[1]), .ZN (n_2));
  inv0d0 g210(.I (wr_ptr_addr_sync[0]), .ZN (n_1));
  inv0d0 g211(.I (wr_ptr_addr_sync[2]), .ZN (n_0));
  dfcrb1 \rd_addr_bin_r_reg[4] (.CDN (rd_rst), .CP (rd_clk), .D
       (rd_addr_bin_next[4]), .Q (rd_addr_grey[4]), .QN (n_10));
endmodule

module fifo_full(wr_clk, wr_en, wr_rst, rd_ptr_addr_sync, full,
     wr_addr_grey, wr_addr_bin);
  input wr_clk, wr_en, wr_rst;
  input [4:0] rd_ptr_addr_sync;
  output full;
  output [4:0] wr_addr_grey;
  output [3:0] wr_addr_bin;
  wire wr_clk, wr_en, wr_rst;
  wire [4:0] rd_ptr_addr_sync;
  wire full;
  wire [4:0] wr_addr_grey;
  wire [3:0] wr_addr_bin;
  wire [4:0] wr_addr_grey_next;
  wire [4:0] wr_addr_binary_next;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16;
  inv0d0 g162(.I (wr_en), .ZN (n_16));
  dfcrq1 \wr_addr_grey_reg[3] (.CDN (wr_rst), .CP (wr_clk), .D
       (wr_addr_grey_next[3]), .Q (wr_addr_grey[3]));
  mx02d1 g212__7482(.I0 (wr_addr_binary_next[4]), .I1 (n_15), .S
       (wr_addr_binary_next[3]), .Z (wr_addr_grey_next[3]));
  dfcrq1 \wr_addr_grey_reg[2] (.CDN (wr_rst), .CP (wr_clk), .D
       (wr_addr_grey_next[2]), .Q (wr_addr_grey[2]));
  inv0d0 g214(.I (n_15), .ZN (wr_addr_binary_next[4]));
  aoim22d1 g215__4733(.A1 (n_14), .A2 (wr_addr_grey[4]), .B1 (n_14),
       .B2 (wr_addr_grey[4]), .Z (n_15));
  xr02d1 g216__6161(.A1 (wr_addr_binary_next[3]), .A2
       (wr_addr_binary_next[2]), .Z (wr_addr_grey_next[2]));
  inv0d0 g217(.I (n_13), .ZN (n_14));
  ah01d1 g218__9315(.A (n_12), .B (wr_addr_bin[3]), .CO (n_13), .S
       (wr_addr_binary_next[3]));
  dfcrq1 \wr_addr_grey_reg[1] (.CDN (wr_rst), .CP (wr_clk), .D
       (wr_addr_grey_next[1]), .Q (wr_addr_grey[1]));
  xr02d1 g220__9945(.A1 (wr_addr_binary_next[2]), .A2
       (wr_addr_binary_next[1]), .Z (wr_addr_grey_next[1]));
  ah01d1 g221__2883(.A (n_11), .B (wr_addr_bin[2]), .CO (n_12), .S
       (wr_addr_binary_next[2]));
  dfcrq1 \wr_addr_grey_reg[0] (.CDN (wr_rst), .CP (wr_clk), .D
       (wr_addr_grey_next[0]), .Q (wr_addr_grey[0]));
  xr02d1 g223__2346(.A1 (wr_addr_binary_next[1]), .A2
       (wr_addr_binary_next[0]), .Z (wr_addr_grey_next[0]));
  ah01d1 g224__1666(.A (n_10), .B (wr_addr_bin[1]), .CO (n_11), .S
       (wr_addr_binary_next[1]));
  ah01d1 g225__7410(.A (n_9), .B (wr_addr_bin[0]), .CO (n_10), .S
       (wr_addr_binary_next[0]));
  nr02d1 g226__6417(.A1 (full), .A2 (n_16), .ZN (n_9));
  dfcrq1 full_r_reg(.CDN (wr_rst), .CP (wr_clk), .D (n_8), .Q (full));
  nr04d1 g227__5477(.A1 (n_5), .A2 (n_4), .A3 (n_6), .A4 (n_7), .ZN
       (n_8));
  oai211d1 g228__2398(.A (n_2), .B (n_3), .C1 (wr_addr_grey_next[3]),
       .C2 (rd_ptr_addr_sync[3]), .ZN (n_7));
  aoim22d1 g229__5107(.A1 (wr_addr_grey_next[2]), .A2
       (rd_ptr_addr_sync[2]), .B1 (wr_addr_grey_next[2]), .B2
       (rd_ptr_addr_sync[2]), .Z (n_6));
  aoim22d1 g230__6260(.A1 (wr_addr_grey_next[0]), .A2
       (rd_ptr_addr_sync[0]), .B1 (wr_addr_grey_next[0]), .B2
       (rd_ptr_addr_sync[0]), .Z (n_5));
  aoim22d1 g231__4319(.A1 (wr_addr_binary_next[4]), .A2 (n_0), .B1
       (wr_addr_binary_next[4]), .B2 (n_0), .Z (n_4));
  aoim22d1 g232__8428(.A1 (n_1), .A2 (rd_ptr_addr_sync[1]), .B1 (n_1),
       .B2 (rd_ptr_addr_sync[1]), .Z (n_3));
  dfcrq1 \wr_addr_bin_r_reg[0] (.CDN (wr_rst), .CP (wr_clk), .D
       (wr_addr_binary_next[0]), .Q (wr_addr_bin[0]));
  dfcrq1 \wr_addr_bin_r_reg[1] (.CDN (wr_rst), .CP (wr_clk), .D
       (wr_addr_binary_next[1]), .Q (wr_addr_bin[1]));
  dfcrq1 \wr_addr_bin_r_reg[2] (.CDN (wr_rst), .CP (wr_clk), .D
       (wr_addr_binary_next[2]), .Q (wr_addr_bin[2]));
  dfcrq1 \wr_addr_bin_r_reg[4] (.CDN (wr_rst), .CP (wr_clk), .D
       (wr_addr_binary_next[4]), .Q (wr_addr_grey[4]));
  dfcrq1 \wr_addr_bin_r_reg[3] (.CDN (wr_rst), .CP (wr_clk), .D
       (wr_addr_binary_next[3]), .Q (wr_addr_bin[3]));
  nd02d1 g237__5526(.A1 (wr_addr_grey_next[3]), .A2
       (rd_ptr_addr_sync[3]), .ZN (n_2));
  inv0d0 g238(.I (wr_addr_grey_next[1]), .ZN (n_1));
  inv0d0 g239(.I (rd_ptr_addr_sync[4]), .ZN (n_0));
endmodule

module fifo_memory(clk, rst, wr_en, full, wr_addr, rd_addr, wr_data,
     rd_data);
  input clk, rst, wr_en, full;
  input [3:0] wr_addr, rd_addr;
  input [7:0] wr_data;
  output [7:0] rd_data;
  wire clk, rst, wr_en, full;
  wire [3:0] wr_addr, rd_addr;
  wire [7:0] wr_data;
  wire [7:0] rd_data;
  wire [7:0] \mem[8] ;
  wire [7:0] \mem[9] ;
  wire [7:0] \mem[0] ;
  wire [7:0] \mem[1] ;
  wire [7:0] \mem[4] ;
  wire [7:0] \mem[5] ;
  wire [7:0] \mem[2] ;
  wire [7:0] \mem[3] ;
  wire [7:0] \mem[14] ;
  wire [7:0] \mem[15] ;
  wire [7:0] \mem[10] ;
  wire [7:0] \mem[11] ;
  wire [7:0] \mem[6] ;
  wire [7:0] \mem[7] ;
  wire [7:0] \mem[12] ;
  wire [7:0] \mem[13] ;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_100, n_101, n_102, n_103;
  wire n_104, n_105, n_106, n_107, n_108, n_109, n_110, n_111;
  wire n_112, n_113, n_114, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_124, n_125, n_126, n_127;
  wire n_128;
  nd04d1 g3106__6783(.A1 (n_103), .A2 (n_128), .A3 (n_111), .A4 (n_64),
       .ZN (rd_data[2]));
  nd04d1 g3107__3680(.A1 (n_94), .A2 (n_122), .A3 (n_106), .A4 (n_59),
       .ZN (rd_data[6]));
  nd04d1 g3108__1617(.A1 (n_70), .A2 (n_126), .A3 (n_112), .A4 (n_57),
       .ZN (rd_data[7]));
  nd04d1 g3109__2802(.A1 (n_95), .A2 (n_125), .A3 (n_109), .A4 (n_61),
       .ZN (rd_data[1]));
  nd04d1 g3110__1705(.A1 (n_66), .A2 (n_127), .A3 (n_110), .A4 (n_63),
       .ZN (rd_data[5]));
  nd04d1 g3111__5122(.A1 (n_85), .A2 (n_124), .A3 (n_108), .A4 (n_62),
       .ZN (rd_data[0]));
  nd04d1 g3112__8246(.A1 (n_89), .A2 (n_123), .A3 (n_107), .A4 (n_58),
       .ZN (rd_data[4]));
  nd04d1 g3113__7098(.A1 (n_73), .A2 (n_121), .A3 (n_105), .A4 (n_60),
       .ZN (rd_data[3]));
  aoi221d1 g3114__6131(.A (n_118), .B1 (n_42), .B2 (\mem[8] [2]), .C1
       (\mem[9] [2]), .C2 (n_46), .ZN (n_128));
  aoi221d1 g3115__1881(.A (n_119), .B1 (n_41), .B2 (\mem[0] [5]), .C1
       (\mem[1] [5]), .C2 (n_51), .ZN (n_127));
  aoi221d1 g3116__5115(.A (n_117), .B1 (n_56), .B2 (\mem[4] [7]), .C1
       (\mem[5] [7]), .C2 (n_53), .ZN (n_126));
  aoi221d1 g3117__7482(.A (n_120), .B1 (n_54), .B2 (\mem[2] [1]), .C1
       (\mem[3] [1]), .C2 (n_47), .ZN (n_125));
  aoi221d1 g3118__4733(.A (n_114), .B1 (n_54), .B2 (\mem[2] [0]), .C1
       (\mem[3] [0]), .C2 (n_47), .ZN (n_124));
  aoi221d1 g3119__6161(.A (n_115), .B1 (n_55), .B2 (\mem[14] [4]), .C1
       (\mem[15] [4]), .C2 (n_52), .ZN (n_123));
  aoi221d1 g3120__9315(.A (n_116), .B1 (n_44), .B2 (\mem[10] [6]), .C1
       (\mem[11] [6]), .C2 (n_48), .ZN (n_122));
  aoi221d1 g3121__9945(.A (n_113), .B1 (n_45), .B2 (\mem[6] [3]), .C1
       (\mem[7] [3]), .C2 (n_50), .ZN (n_121));
  nd04d1 g3122__2883(.A1 (n_87), .A2 (n_91), .A3 (n_88), .A4 (n_90),
       .ZN (n_120));
  nd04d1 g3123__2346(.A1 (n_99), .A2 (n_93), .A3 (n_92), .A4 (n_96),
       .ZN (n_119));
  nd04d1 g3124__1666(.A1 (n_100), .A2 (n_98), .A3 (n_97), .A4 (n_101),
       .ZN (n_118));
  nd04d1 g3125__7410(.A1 (n_102), .A2 (n_68), .A3 (n_86), .A4 (n_76),
       .ZN (n_117));
  nd04d1 g3126__6417(.A1 (n_80), .A2 (n_72), .A3 (n_71), .A4 (n_75),
       .ZN (n_116));
  nd04d1 g3127__5477(.A1 (n_74), .A2 (n_77), .A3 (n_79), .A4 (n_83),
       .ZN (n_115));
  nd04d1 g3128__2398(.A1 (n_78), .A2 (n_82), .A3 (n_81), .A4 (n_84),
       .ZN (n_114));
  nd04d1 g3129__5107(.A1 (n_67), .A2 (n_65), .A3 (n_104), .A4 (n_69),
       .ZN (n_113));
  aoi222d1 g3130__6260(.A1 (\mem[1] [7]), .A2 (n_51), .B1 (n_45), .B2
       (\mem[6] [7]), .C1 (\mem[7] [7]), .C2 (n_50), .ZN (n_112));
  aoi222d1 g3131__4319(.A1 (\mem[10] [2]), .A2 (n_44), .B1 (n_55), .B2
       (\mem[14] [2]), .C1 (\mem[11] [2]), .C2 (n_48), .ZN (n_111));
  aoi222d1 g3132__8428(.A1 (\mem[2] [5]), .A2 (n_54), .B1 (n_45), .B2
       (\mem[6] [5]), .C1 (\mem[3] [5]), .C2 (n_47), .ZN (n_110));
  aoi222d1 g3133__5526(.A1 (\mem[4] [1]), .A2 (n_56), .B1 (n_50), .B2
       (\mem[7] [1]), .C1 (\mem[5] [1]), .C2 (n_53), .ZN (n_109));
  aoi222d1 g3134__6783(.A1 (\mem[4] [0]), .A2 (n_56), .B1 (n_50), .B2
       (\mem[7] [0]), .C1 (\mem[5] [0]), .C2 (n_53), .ZN (n_108));
  aoi222d1 g3135__3680(.A1 (\mem[10] [4]), .A2 (n_44), .B1 (n_42), .B2
       (\mem[8] [4]), .C1 (\mem[9] [4]), .C2 (n_46), .ZN (n_107));
  aoi222d1 g3136__1617(.A1 (\mem[8] [6]), .A2 (n_42), .B1 (n_49), .B2
       (\mem[12] [6]), .C1 (\mem[13] [6]), .C2 (n_43), .ZN (n_106));
  aoi222d1 g3137__2802(.A1 (\mem[0] [3]), .A2 (n_41), .B1 (n_47), .B2
       (\mem[3] [3]), .C1 (\mem[1] [3]), .C2 (n_51), .ZN (n_105));
  aoi22d1 g3138__1705(.A1 (n_44), .A2 (\mem[10] [3]), .B1 (n_48), .B2
       (\mem[11] [3]), .ZN (n_104));
  aoi22d1 g3139__5122(.A1 (n_49), .A2 (\mem[12] [2]), .B1 (n_52), .B2
       (\mem[15] [2]), .ZN (n_103));
  aoi22d1 g3140__8246(.A1 (n_49), .A2 (\mem[12] [7]), .B1 (n_43), .B2
       (\mem[13] [7]), .ZN (n_102));
  aoi22d1 g3141__7098(.A1 (n_45), .A2 (\mem[6] [2]), .B1 (n_50), .B2
       (\mem[7] [2]), .ZN (n_101));
  aoi22d1 g3142__6131(.A1 (n_56), .A2 (\mem[4] [2]), .B1 (n_53), .B2
       (\mem[5] [2]), .ZN (n_100));
  aoi22d1 g3143__1881(.A1 (n_42), .A2 (\mem[8] [5]), .B1 (n_46), .B2
       (\mem[9] [5]), .ZN (n_99));
  aoi22d1 g3144__5115(.A1 (n_54), .A2 (\mem[2] [2]), .B1 (n_47), .B2
       (\mem[3] [2]), .ZN (n_98));
  aoi22d1 g3145__7482(.A1 (n_41), .A2 (\mem[0] [2]), .B1 (n_51), .B2
       (\mem[1] [2]), .ZN (n_97));
  aoi22d1 g3146__4733(.A1 (n_49), .A2 (\mem[12] [5]), .B1 (n_43), .B2
       (\mem[13] [5]), .ZN (n_96));
  aoi22d1 g3147__6161(.A1 (n_41), .A2 (\mem[0] [1]), .B1 (n_45), .B2
       (\mem[6] [1]), .ZN (n_95));
  aoi22d1 g3148__9315(.A1 (n_46), .A2 (\mem[9] [6]), .B1 (n_55), .B2
       (\mem[14] [6]), .ZN (n_94));
  aoi22d1 g3149__9945(.A1 (n_55), .A2 (\mem[14] [5]), .B1 (n_52), .B2
       (\mem[15] [5]), .ZN (n_93));
  aoi22d1 g3150__2883(.A1 (n_44), .A2 (\mem[10] [5]), .B1 (n_48), .B2
       (\mem[11] [5]), .ZN (n_92));
  aoi22d1 g3151__2346(.A1 (n_55), .A2 (\mem[14] [1]), .B1 (n_52), .B2
       (\mem[15] [1]), .ZN (n_91));
  aoi22d1 g3152__1666(.A1 (n_49), .A2 (\mem[12] [1]), .B1 (n_43), .B2
       (\mem[13] [1]), .ZN (n_90));
  aoi22d1 g3153__7410(.A1 (n_49), .A2 (\mem[12] [4]), .B1 (n_48), .B2
       (\mem[11] [4]), .ZN (n_89));
  aoi22d1 g3154__6417(.A1 (n_44), .A2 (\mem[10] [1]), .B1 (n_48), .B2
       (\mem[11] [1]), .ZN (n_88));
  aoi22d1 g3155__5477(.A1 (n_42), .A2 (\mem[8] [1]), .B1 (n_46), .B2
       (\mem[9] [1]), .ZN (n_87));
  aoi22d1 g3156__2398(.A1 (n_44), .A2 (\mem[10] [7]), .B1 (n_48), .B2
       (\mem[11] [7]), .ZN (n_86));
  aoi22d1 g3157__5107(.A1 (n_51), .A2 (\mem[1] [0]), .B1 (n_45), .B2
       (\mem[6] [0]), .ZN (n_85));
  aoi22d1 g3158__6260(.A1 (n_49), .A2 (\mem[12] [0]), .B1 (n_43), .B2
       (\mem[13] [0]), .ZN (n_84));
  aoi22d1 g3159__4319(.A1 (n_45), .A2 (\mem[6] [4]), .B1 (n_50), .B2
       (\mem[7] [4]), .ZN (n_83));
  aoi22d1 g3160__8428(.A1 (n_55), .A2 (\mem[14] [0]), .B1 (n_52), .B2
       (\mem[15] [0]), .ZN (n_82));
  aoi22d1 g3161__5526(.A1 (n_44), .A2 (\mem[10] [0]), .B1 (n_48), .B2
       (\mem[11] [0]), .ZN (n_81));
  aoi22d1 g3162__6783(.A1 (n_56), .A2 (\mem[4] [6]), .B1 (n_53), .B2
       (\mem[5] [6]), .ZN (n_80));
  aoi22d1 g3163__3680(.A1 (n_41), .A2 (\mem[0] [4]), .B1 (n_51), .B2
       (\mem[1] [4]), .ZN (n_79));
  aoi22d1 g3164__1617(.A1 (n_42), .A2 (\mem[8] [0]), .B1 (n_46), .B2
       (\mem[9] [0]), .ZN (n_78));
  aoi22d1 g3165__2802(.A1 (n_54), .A2 (\mem[2] [4]), .B1 (n_47), .B2
       (\mem[3] [4]), .ZN (n_77));
  aoi22d1 g3166__1705(.A1 (n_42), .A2 (\mem[8] [7]), .B1 (n_46), .B2
       (\mem[9] [7]), .ZN (n_76));
  aoi22d1 g3167__5122(.A1 (n_45), .A2 (\mem[6] [6]), .B1 (n_50), .B2
       (\mem[7] [6]), .ZN (n_75));
  aoi22d1 g3168__8246(.A1 (n_56), .A2 (\mem[4] [4]), .B1 (n_53), .B2
       (\mem[5] [4]), .ZN (n_74));
  aoi22d1 g3169__7098(.A1 (n_56), .A2 (\mem[4] [3]), .B1 (n_54), .B2
       (\mem[2] [3]), .ZN (n_73));
  aoi22d1 g3170__6131(.A1 (n_54), .A2 (\mem[2] [6]), .B1 (n_47), .B2
       (\mem[3] [6]), .ZN (n_72));
  aoi22d1 g3171__1881(.A1 (n_41), .A2 (\mem[0] [6]), .B1 (n_51), .B2
       (\mem[1] [6]), .ZN (n_71));
  aoi22d1 g3172__5115(.A1 (n_41), .A2 (\mem[0] [7]), .B1 (n_47), .B2
       (\mem[3] [7]), .ZN (n_70));
  aoi22d1 g3173__7482(.A1 (n_49), .A2 (\mem[12] [3]), .B1 (n_43), .B2
       (\mem[13] [3]), .ZN (n_69));
  aoi22d1 g3174__4733(.A1 (n_55), .A2 (\mem[14] [7]), .B1 (n_52), .B2
       (\mem[15] [7]), .ZN (n_68));
  aoi22d1 g3175__6161(.A1 (n_42), .A2 (\mem[8] [3]), .B1 (n_46), .B2
       (\mem[9] [3]), .ZN (n_67));
  aoi22d1 g3176__9315(.A1 (n_56), .A2 (\mem[4] [5]), .B1 (n_50), .B2
       (\mem[7] [5]), .ZN (n_66));
  aoi22d1 g3177__9945(.A1 (n_55), .A2 (\mem[14] [3]), .B1 (n_52), .B2
       (\mem[15] [3]), .ZN (n_65));
  nd02d1 g3178__2883(.A1 (n_43), .A2 (\mem[13] [2]), .ZN (n_64));
  nd02d1 g3179__2346(.A1 (n_53), .A2 (\mem[5] [5]), .ZN (n_63));
  nd02d1 g3180__1666(.A1 (n_41), .A2 (\mem[0] [0]), .ZN (n_62));
  nd02d1 g3181__7410(.A1 (n_51), .A2 (\mem[1] [1]), .ZN (n_61));
  nd02d1 g3182__6417(.A1 (n_53), .A2 (\mem[5] [3]), .ZN (n_60));
  nd02d1 g3183__5477(.A1 (n_52), .A2 (\mem[15] [6]), .ZN (n_59));
  nd02d1 g3184__2398(.A1 (n_43), .A2 (\mem[13] [4]), .ZN (n_58));
  nd02d1 g3185__5107(.A1 (n_54), .A2 (\mem[2] [7]), .ZN (n_57));
  nr02d1 g3186__6260(.A1 (n_35), .A2 (n_39), .ZN (n_56));
  nr02d1 g3187__4319(.A1 (n_36), .A2 (n_40), .ZN (n_55));
  nr02d1 g3188__8428(.A1 (n_35), .A2 (n_38), .ZN (n_54));
  nr02d1 g3189__5526(.A1 (n_39), .A2 (n_37), .ZN (n_53));
  nr02d1 g3190__6783(.A1 (n_36), .A2 (n_33), .ZN (n_52));
  nr02d1 g3191__3680(.A1 (n_34), .A2 (n_37), .ZN (n_51));
  nr02d1 g3192__1617(.A1 (n_36), .A2 (n_37), .ZN (n_50));
  nr02d1 g3193__2802(.A1 (n_40), .A2 (n_39), .ZN (n_49));
  nr02d1 g3194__1705(.A1 (n_33), .A2 (n_38), .ZN (n_48));
  nr02d1 g3195__5122(.A1 (n_38), .A2 (n_37), .ZN (n_47));
  nr02d1 g3196__8246(.A1 (n_33), .A2 (n_34), .ZN (n_46));
  nr02d1 g3197__7098(.A1 (n_36), .A2 (n_35), .ZN (n_45));
  nr02d1 g3198__6131(.A1 (n_40), .A2 (n_38), .ZN (n_44));
  nr02d1 g3199__1881(.A1 (n_33), .A2 (n_39), .ZN (n_43));
  nr02d1 g3200__5115(.A1 (n_34), .A2 (n_40), .ZN (n_42));
  nr02d1 g3201__7482(.A1 (n_34), .A2 (n_35), .ZN (n_41));
  nd12d1 g3202__4733(.A1 (rd_addr[0]), .A2 (rd_addr[3]), .ZN (n_40));
  nd12d1 g3203__6161(.A1 (rd_addr[1]), .A2 (rd_addr[2]), .ZN (n_39));
  nd12d1 g3204__9315(.A1 (rd_addr[2]), .A2 (rd_addr[1]), .ZN (n_38));
  nd12d1 g3205__9945(.A1 (rd_addr[3]), .A2 (rd_addr[0]), .ZN (n_37));
  nd02d1 g3206__2883(.A1 (rd_addr[2]), .A2 (rd_addr[1]), .ZN (n_36));
  or02d1 g3207__2346(.A1 (rd_addr[0]), .A2 (rd_addr[3]), .Z (n_35));
  or02d1 g3208__1666(.A1 (rd_addr[1]), .A2 (rd_addr[2]), .Z (n_34));
  nd02d1 g3209__7410(.A1 (rd_addr[3]), .A2 (rd_addr[0]), .ZN (n_33));
  decrq1 \mem_reg[0][0] (.CDN (rst), .CP (clk), .D (wr_data[0]), .ENN
       (n_23), .Q (\mem[0] [0]));
  decrq1 \mem_reg[0][1] (.CDN (rst), .CP (clk), .D (wr_data[1]), .ENN
       (n_23), .Q (\mem[0] [1]));
  decrq1 \mem_reg[0][2] (.CDN (rst), .CP (clk), .D (wr_data[2]), .ENN
       (n_23), .Q (\mem[0] [2]));
  decrq1 \mem_reg[0][3] (.CDN (rst), .CP (clk), .D (wr_data[3]), .ENN
       (n_23), .Q (\mem[0] [3]));
  decrq1 \mem_reg[0][4] (.CDN (rst), .CP (clk), .D (wr_data[4]), .ENN
       (n_23), .Q (\mem[0] [4]));
  decrq1 \mem_reg[0][5] (.CDN (rst), .CP (clk), .D (wr_data[5]), .ENN
       (n_23), .Q (\mem[0] [5]));
  decrq1 \mem_reg[0][6] (.CDN (rst), .CP (clk), .D (wr_data[6]), .ENN
       (n_23), .Q (\mem[0] [6]));
  decrq1 \mem_reg[0][7] (.CDN (rst), .CP (clk), .D (wr_data[7]), .ENN
       (n_23), .Q (\mem[0] [7]));
  decrq1 \mem_reg[1][0] (.CDN (rst), .CP (clk), .D (wr_data[0]), .ENN
       (n_31), .Q (\mem[1] [0]));
  decrq1 \mem_reg[1][1] (.CDN (rst), .CP (clk), .D (wr_data[1]), .ENN
       (n_31), .Q (\mem[1] [1]));
  decrq1 \mem_reg[1][2] (.CDN (rst), .CP (clk), .D (wr_data[2]), .ENN
       (n_31), .Q (\mem[1] [2]));
  decrq1 \mem_reg[1][3] (.CDN (rst), .CP (clk), .D (wr_data[3]), .ENN
       (n_31), .Q (\mem[1] [3]));
  decrq1 \mem_reg[1][4] (.CDN (rst), .CP (clk), .D (wr_data[4]), .ENN
       (n_31), .Q (\mem[1] [4]));
  decrq1 \mem_reg[1][5] (.CDN (rst), .CP (clk), .D (wr_data[5]), .ENN
       (n_31), .Q (\mem[1] [5]));
  decrq1 \mem_reg[1][6] (.CDN (rst), .CP (clk), .D (wr_data[6]), .ENN
       (n_31), .Q (\mem[1] [6]));
  decrq1 \mem_reg[1][7] (.CDN (rst), .CP (clk), .D (wr_data[7]), .ENN
       (n_31), .Q (\mem[1] [7]));
  decrq1 \mem_reg[2][0] (.CDN (rst), .CP (clk), .D (wr_data[0]), .ENN
       (n_26), .Q (\mem[2] [0]));
  decrq1 \mem_reg[2][1] (.CDN (rst), .CP (clk), .D (wr_data[1]), .ENN
       (n_26), .Q (\mem[2] [1]));
  decrq1 \mem_reg[2][2] (.CDN (rst), .CP (clk), .D (wr_data[2]), .ENN
       (n_26), .Q (\mem[2] [2]));
  decrq1 \mem_reg[2][3] (.CDN (rst), .CP (clk), .D (wr_data[3]), .ENN
       (n_26), .Q (\mem[2] [3]));
  decrq1 \mem_reg[2][4] (.CDN (rst), .CP (clk), .D (wr_data[4]), .ENN
       (n_26), .Q (\mem[2] [4]));
  decrq1 \mem_reg[2][5] (.CDN (rst), .CP (clk), .D (wr_data[5]), .ENN
       (n_26), .Q (\mem[2] [5]));
  decrq1 \mem_reg[2][6] (.CDN (rst), .CP (clk), .D (wr_data[6]), .ENN
       (n_26), .Q (\mem[2] [6]));
  decrq1 \mem_reg[2][7] (.CDN (rst), .CP (clk), .D (wr_data[7]), .ENN
       (n_26), .Q (\mem[2] [7]));
  decrq1 \mem_reg[3][0] (.CDN (rst), .CP (clk), .D (wr_data[0]), .ENN
       (n_25), .Q (\mem[3] [0]));
  decrq1 \mem_reg[3][1] (.CDN (rst), .CP (clk), .D (wr_data[1]), .ENN
       (n_25), .Q (\mem[3] [1]));
  decrq1 \mem_reg[3][2] (.CDN (rst), .CP (clk), .D (wr_data[2]), .ENN
       (n_25), .Q (\mem[3] [2]));
  decrq1 \mem_reg[3][3] (.CDN (rst), .CP (clk), .D (wr_data[3]), .ENN
       (n_25), .Q (\mem[3] [3]));
  decrq1 \mem_reg[3][4] (.CDN (rst), .CP (clk), .D (wr_data[4]), .ENN
       (n_25), .Q (\mem[3] [4]));
  decrq1 \mem_reg[3][5] (.CDN (rst), .CP (clk), .D (wr_data[5]), .ENN
       (n_25), .Q (\mem[3] [5]));
  decrq1 \mem_reg[3][6] (.CDN (rst), .CP (clk), .D (wr_data[6]), .ENN
       (n_25), .Q (\mem[3] [6]));
  decrq1 \mem_reg[3][7] (.CDN (rst), .CP (clk), .D (wr_data[7]), .ENN
       (n_25), .Q (\mem[3] [7]));
  decrq1 \mem_reg[4][0] (.CDN (rst), .CP (clk), .D (wr_data[0]), .ENN
       (n_21), .Q (\mem[4] [0]));
  decrq1 \mem_reg[4][1] (.CDN (rst), .CP (clk), .D (wr_data[1]), .ENN
       (n_21), .Q (\mem[4] [1]));
  decrq1 \mem_reg[4][2] (.CDN (rst), .CP (clk), .D (wr_data[2]), .ENN
       (n_21), .Q (\mem[4] [2]));
  decrq1 \mem_reg[4][3] (.CDN (rst), .CP (clk), .D (wr_data[3]), .ENN
       (n_21), .Q (\mem[4] [3]));
  decrq1 \mem_reg[4][4] (.CDN (rst), .CP (clk), .D (wr_data[4]), .ENN
       (n_21), .Q (\mem[4] [4]));
  decrq1 \mem_reg[4][5] (.CDN (rst), .CP (clk), .D (wr_data[5]), .ENN
       (n_21), .Q (\mem[4] [5]));
  decrq1 \mem_reg[4][6] (.CDN (rst), .CP (clk), .D (wr_data[6]), .ENN
       (n_21), .Q (\mem[4] [6]));
  decrq1 \mem_reg[4][7] (.CDN (rst), .CP (clk), .D (wr_data[7]), .ENN
       (n_21), .Q (\mem[4] [7]));
  decrq1 \mem_reg[5][0] (.CDN (rst), .CP (clk), .D (wr_data[0]), .ENN
       (n_18), .Q (\mem[5] [0]));
  decrq1 \mem_reg[5][1] (.CDN (rst), .CP (clk), .D (wr_data[1]), .ENN
       (n_18), .Q (\mem[5] [1]));
  decrq1 \mem_reg[5][2] (.CDN (rst), .CP (clk), .D (wr_data[2]), .ENN
       (n_18), .Q (\mem[5] [2]));
  decrq1 \mem_reg[5][3] (.CDN (rst), .CP (clk), .D (wr_data[3]), .ENN
       (n_18), .Q (\mem[5] [3]));
  decrq1 \mem_reg[5][4] (.CDN (rst), .CP (clk), .D (wr_data[4]), .ENN
       (n_18), .Q (\mem[5] [4]));
  decrq1 \mem_reg[5][5] (.CDN (rst), .CP (clk), .D (wr_data[5]), .ENN
       (n_18), .Q (\mem[5] [5]));
  decrq1 \mem_reg[5][6] (.CDN (rst), .CP (clk), .D (wr_data[6]), .ENN
       (n_18), .Q (\mem[5] [6]));
  decrq1 \mem_reg[5][7] (.CDN (rst), .CP (clk), .D (wr_data[7]), .ENN
       (n_18), .Q (\mem[5] [7]));
  decrq1 \mem_reg[6][0] (.CDN (rst), .CP (clk), .D (wr_data[0]), .ENN
       (n_30), .Q (\mem[6] [0]));
  decrq1 \mem_reg[6][1] (.CDN (rst), .CP (clk), .D (wr_data[1]), .ENN
       (n_30), .Q (\mem[6] [1]));
  decrq1 \mem_reg[6][2] (.CDN (rst), .CP (clk), .D (wr_data[2]), .ENN
       (n_30), .Q (\mem[6] [2]));
  decrq1 \mem_reg[6][3] (.CDN (rst), .CP (clk), .D (wr_data[3]), .ENN
       (n_30), .Q (\mem[6] [3]));
  decrq1 \mem_reg[6][4] (.CDN (rst), .CP (clk), .D (wr_data[4]), .ENN
       (n_30), .Q (\mem[6] [4]));
  decrq1 \mem_reg[6][5] (.CDN (rst), .CP (clk), .D (wr_data[5]), .ENN
       (n_30), .Q (\mem[6] [5]));
  decrq1 \mem_reg[6][6] (.CDN (rst), .CP (clk), .D (wr_data[6]), .ENN
       (n_30), .Q (\mem[6] [6]));
  decrq1 \mem_reg[6][7] (.CDN (rst), .CP (clk), .D (wr_data[7]), .ENN
       (n_30), .Q (\mem[6] [7]));
  decrq1 \mem_reg[7][0] (.CDN (rst), .CP (clk), .D (wr_data[0]), .ENN
       (n_29), .Q (\mem[7] [0]));
  decrq1 \mem_reg[7][1] (.CDN (rst), .CP (clk), .D (wr_data[1]), .ENN
       (n_29), .Q (\mem[7] [1]));
  decrq1 \mem_reg[7][2] (.CDN (rst), .CP (clk), .D (wr_data[2]), .ENN
       (n_29), .Q (\mem[7] [2]));
  decrq1 \mem_reg[7][3] (.CDN (rst), .CP (clk), .D (wr_data[3]), .ENN
       (n_29), .Q (\mem[7] [3]));
  decrq1 \mem_reg[7][4] (.CDN (rst), .CP (clk), .D (wr_data[4]), .ENN
       (n_29), .Q (\mem[7] [4]));
  decrq1 \mem_reg[7][5] (.CDN (rst), .CP (clk), .D (wr_data[5]), .ENN
       (n_29), .Q (\mem[7] [5]));
  decrq1 \mem_reg[7][6] (.CDN (rst), .CP (clk), .D (wr_data[6]), .ENN
       (n_29), .Q (\mem[7] [6]));
  decrq1 \mem_reg[7][7] (.CDN (rst), .CP (clk), .D (wr_data[7]), .ENN
       (n_29), .Q (\mem[7] [7]));
  decrq1 \mem_reg[8][0] (.CDN (rst), .CP (clk), .D (wr_data[0]), .ENN
       (n_32), .Q (\mem[8] [0]));
  decrq1 \mem_reg[8][1] (.CDN (rst), .CP (clk), .D (wr_data[1]), .ENN
       (n_32), .Q (\mem[8] [1]));
  decrq1 \mem_reg[8][2] (.CDN (rst), .CP (clk), .D (wr_data[2]), .ENN
       (n_32), .Q (\mem[8] [2]));
  decrq1 \mem_reg[8][3] (.CDN (rst), .CP (clk), .D (wr_data[3]), .ENN
       (n_32), .Q (\mem[8] [3]));
  decrq1 \mem_reg[8][4] (.CDN (rst), .CP (clk), .D (wr_data[4]), .ENN
       (n_32), .Q (\mem[8] [4]));
  decrq1 \mem_reg[8][5] (.CDN (rst), .CP (clk), .D (wr_data[5]), .ENN
       (n_32), .Q (\mem[8] [5]));
  decrq1 \mem_reg[8][6] (.CDN (rst), .CP (clk), .D (wr_data[6]), .ENN
       (n_32), .Q (\mem[8] [6]));
  decrq1 \mem_reg[8][7] (.CDN (rst), .CP (clk), .D (wr_data[7]), .ENN
       (n_32), .Q (\mem[8] [7]));
  decrq1 \mem_reg[9][0] (.CDN (rst), .CP (clk), .D (wr_data[0]), .ENN
       (n_20), .Q (\mem[9] [0]));
  decrq1 \mem_reg[9][1] (.CDN (rst), .CP (clk), .D (wr_data[1]), .ENN
       (n_20), .Q (\mem[9] [1]));
  decrq1 \mem_reg[9][2] (.CDN (rst), .CP (clk), .D (wr_data[2]), .ENN
       (n_20), .Q (\mem[9] [2]));
  decrq1 \mem_reg[9][3] (.CDN (rst), .CP (clk), .D (wr_data[3]), .ENN
       (n_20), .Q (\mem[9] [3]));
  decrq1 \mem_reg[9][4] (.CDN (rst), .CP (clk), .D (wr_data[4]), .ENN
       (n_20), .Q (\mem[9] [4]));
  decrq1 \mem_reg[9][5] (.CDN (rst), .CP (clk), .D (wr_data[5]), .ENN
       (n_20), .Q (\mem[9] [5]));
  decrq1 \mem_reg[9][6] (.CDN (rst), .CP (clk), .D (wr_data[6]), .ENN
       (n_20), .Q (\mem[9] [6]));
  decrq1 \mem_reg[9][7] (.CDN (rst), .CP (clk), .D (wr_data[7]), .ENN
       (n_20), .Q (\mem[9] [7]));
  decrq1 \mem_reg[10][0] (.CDN (rst), .CP (clk), .D (wr_data[0]), .ENN
       (n_17), .Q (\mem[10] [0]));
  decrq1 \mem_reg[10][1] (.CDN (rst), .CP (clk), .D (wr_data[1]), .ENN
       (n_17), .Q (\mem[10] [1]));
  decrq1 \mem_reg[10][2] (.CDN (rst), .CP (clk), .D (wr_data[2]), .ENN
       (n_17), .Q (\mem[10] [2]));
  decrq1 \mem_reg[10][3] (.CDN (rst), .CP (clk), .D (wr_data[3]), .ENN
       (n_17), .Q (\mem[10] [3]));
  decrq1 \mem_reg[10][4] (.CDN (rst), .CP (clk), .D (wr_data[4]), .ENN
       (n_17), .Q (\mem[10] [4]));
  decrq1 \mem_reg[10][5] (.CDN (rst), .CP (clk), .D (wr_data[5]), .ENN
       (n_17), .Q (\mem[10] [5]));
  decrq1 \mem_reg[10][6] (.CDN (rst), .CP (clk), .D (wr_data[6]), .ENN
       (n_17), .Q (\mem[10] [6]));
  decrq1 \mem_reg[10][7] (.CDN (rst), .CP (clk), .D (wr_data[7]), .ENN
       (n_17), .Q (\mem[10] [7]));
  decrq1 \mem_reg[11][0] (.CDN (rst), .CP (clk), .D (wr_data[0]), .ENN
       (n_22), .Q (\mem[11] [0]));
  decrq1 \mem_reg[11][1] (.CDN (rst), .CP (clk), .D (wr_data[1]), .ENN
       (n_22), .Q (\mem[11] [1]));
  decrq1 \mem_reg[11][2] (.CDN (rst), .CP (clk), .D (wr_data[2]), .ENN
       (n_22), .Q (\mem[11] [2]));
  decrq1 \mem_reg[11][3] (.CDN (rst), .CP (clk), .D (wr_data[3]), .ENN
       (n_22), .Q (\mem[11] [3]));
  decrq1 \mem_reg[11][4] (.CDN (rst), .CP (clk), .D (wr_data[4]), .ENN
       (n_22), .Q (\mem[11] [4]));
  decrq1 \mem_reg[11][5] (.CDN (rst), .CP (clk), .D (wr_data[5]), .ENN
       (n_22), .Q (\mem[11] [5]));
  decrq1 \mem_reg[11][6] (.CDN (rst), .CP (clk), .D (wr_data[6]), .ENN
       (n_22), .Q (\mem[11] [6]));
  decrq1 \mem_reg[11][7] (.CDN (rst), .CP (clk), .D (wr_data[7]), .ENN
       (n_22), .Q (\mem[11] [7]));
  decrq1 \mem_reg[12][0] (.CDN (rst), .CP (clk), .D (wr_data[0]), .ENN
       (n_28), .Q (\mem[12] [0]));
  decrq1 \mem_reg[12][1] (.CDN (rst), .CP (clk), .D (wr_data[1]), .ENN
       (n_28), .Q (\mem[12] [1]));
  decrq1 \mem_reg[12][2] (.CDN (rst), .CP (clk), .D (wr_data[2]), .ENN
       (n_28), .Q (\mem[12] [2]));
  decrq1 \mem_reg[12][3] (.CDN (rst), .CP (clk), .D (wr_data[3]), .ENN
       (n_28), .Q (\mem[12] [3]));
  decrq1 \mem_reg[12][4] (.CDN (rst), .CP (clk), .D (wr_data[4]), .ENN
       (n_28), .Q (\mem[12] [4]));
  decrq1 \mem_reg[12][5] (.CDN (rst), .CP (clk), .D (wr_data[5]), .ENN
       (n_28), .Q (\mem[12] [5]));
  decrq1 \mem_reg[12][6] (.CDN (rst), .CP (clk), .D (wr_data[6]), .ENN
       (n_28), .Q (\mem[12] [6]));
  decrq1 \mem_reg[12][7] (.CDN (rst), .CP (clk), .D (wr_data[7]), .ENN
       (n_28), .Q (\mem[12] [7]));
  decrq1 \mem_reg[13][0] (.CDN (rst), .CP (clk), .D (wr_data[0]), .ENN
       (n_27), .Q (\mem[13] [0]));
  decrq1 \mem_reg[13][1] (.CDN (rst), .CP (clk), .D (wr_data[1]), .ENN
       (n_27), .Q (\mem[13] [1]));
  decrq1 \mem_reg[13][2] (.CDN (rst), .CP (clk), .D (wr_data[2]), .ENN
       (n_27), .Q (\mem[13] [2]));
  decrq1 \mem_reg[13][3] (.CDN (rst), .CP (clk), .D (wr_data[3]), .ENN
       (n_27), .Q (\mem[13] [3]));
  decrq1 \mem_reg[13][4] (.CDN (rst), .CP (clk), .D (wr_data[4]), .ENN
       (n_27), .Q (\mem[13] [4]));
  decrq1 \mem_reg[13][5] (.CDN (rst), .CP (clk), .D (wr_data[5]), .ENN
       (n_27), .Q (\mem[13] [5]));
  decrq1 \mem_reg[13][6] (.CDN (rst), .CP (clk), .D (wr_data[6]), .ENN
       (n_27), .Q (\mem[13] [6]));
  decrq1 \mem_reg[13][7] (.CDN (rst), .CP (clk), .D (wr_data[7]), .ENN
       (n_27), .Q (\mem[13] [7]));
  decrq1 \mem_reg[14][0] (.CDN (rst), .CP (clk), .D (wr_data[0]), .ENN
       (n_19), .Q (\mem[14] [0]));
  decrq1 \mem_reg[14][1] (.CDN (rst), .CP (clk), .D (wr_data[1]), .ENN
       (n_19), .Q (\mem[14] [1]));
  decrq1 \mem_reg[14][2] (.CDN (rst), .CP (clk), .D (wr_data[2]), .ENN
       (n_19), .Q (\mem[14] [2]));
  decrq1 \mem_reg[14][3] (.CDN (rst), .CP (clk), .D (wr_data[3]), .ENN
       (n_19), .Q (\mem[14] [3]));
  decrq1 \mem_reg[14][4] (.CDN (rst), .CP (clk), .D (wr_data[4]), .ENN
       (n_19), .Q (\mem[14] [4]));
  decrq1 \mem_reg[14][5] (.CDN (rst), .CP (clk), .D (wr_data[5]), .ENN
       (n_19), .Q (\mem[14] [5]));
  decrq1 \mem_reg[14][6] (.CDN (rst), .CP (clk), .D (wr_data[6]), .ENN
       (n_19), .Q (\mem[14] [6]));
  decrq1 \mem_reg[14][7] (.CDN (rst), .CP (clk), .D (wr_data[7]), .ENN
       (n_19), .Q (\mem[14] [7]));
  decrq1 \mem_reg[15][0] (.CDN (rst), .CP (clk), .D (wr_data[0]), .ENN
       (n_24), .Q (\mem[15] [0]));
  decrq1 \mem_reg[15][1] (.CDN (rst), .CP (clk), .D (wr_data[1]), .ENN
       (n_24), .Q (\mem[15] [1]));
  decrq1 \mem_reg[15][2] (.CDN (rst), .CP (clk), .D (wr_data[2]), .ENN
       (n_24), .Q (\mem[15] [2]));
  decrq1 \mem_reg[15][3] (.CDN (rst), .CP (clk), .D (wr_data[3]), .ENN
       (n_24), .Q (\mem[15] [3]));
  decrq1 \mem_reg[15][4] (.CDN (rst), .CP (clk), .D (wr_data[4]), .ENN
       (n_24), .Q (\mem[15] [4]));
  decrq1 \mem_reg[15][5] (.CDN (rst), .CP (clk), .D (wr_data[5]), .ENN
       (n_24), .Q (\mem[15] [5]));
  decrq1 \mem_reg[15][6] (.CDN (rst), .CP (clk), .D (wr_data[6]), .ENN
       (n_24), .Q (\mem[15] [6]));
  decrq1 \mem_reg[15][7] (.CDN (rst), .CP (clk), .D (wr_data[7]), .ENN
       (n_24), .Q (\mem[15] [7]));
  or02d1 g1967__6417(.A1 (n_1), .A2 (wr_addr[0]), .Z (n_32));
  nd02d1 g1968__5477(.A1 (n_13), .A2 (wr_addr[0]), .ZN (n_31));
  nd02d1 g1969__2398(.A1 (n_14), .A2 (n_2), .ZN (n_30));
  nd02d1 g1970__5107(.A1 (n_14), .A2 (wr_addr[0]), .ZN (n_29));
  or02d1 g1971__6260(.A1 (n_16), .A2 (wr_addr[0]), .Z (n_28));
  nd12d1 g1972__4319(.A1 (n_16), .A2 (wr_addr[0]), .ZN (n_27));
  nd02d1 g1973__8428(.A1 (n_12), .A2 (n_2), .ZN (n_26));
  nd02d1 g1974__5526(.A1 (n_12), .A2 (wr_addr[0]), .ZN (n_25));
  nd02d1 g1975__6783(.A1 (n_11), .A2 (wr_addr[0]), .ZN (n_24));
  nd02d1 g1976__3680(.A1 (n_13), .A2 (n_2), .ZN (n_23));
  nd02d1 g1977__1617(.A1 (n_15), .A2 (wr_addr[0]), .ZN (n_22));
  nd02d1 g1978__2802(.A1 (n_0), .A2 (n_2), .ZN (n_21));
  nd12d1 g1979__1705(.A1 (n_1), .A2 (wr_addr[0]), .ZN (n_20));
  nd02d1 g1980__5122(.A1 (n_11), .A2 (n_2), .ZN (n_19));
  nd02d1 g1981__8246(.A1 (n_0), .A2 (wr_addr[0]), .ZN (n_18));
  nd02d1 g1982__7098(.A1 (n_15), .A2 (n_2), .ZN (n_17));
  nd02d1 g1984__6131(.A1 (n_8), .A2 (wr_addr[3]), .ZN (n_16));
  nr02d1 g1985__1881(.A1 (n_3), .A2 (n_7), .ZN (n_15));
  nr02d1 g1986__5115(.A1 (wr_addr[3]), .A2 (n_10), .ZN (n_14));
  nr02d1 g1987__7482(.A1 (wr_addr[3]), .A2 (n_9), .ZN (n_13));
  nr02d1 g1988__4733(.A1 (wr_addr[3]), .A2 (n_7), .ZN (n_12));
  nr02d1 g1989__6161(.A1 (n_3), .A2 (n_10), .ZN (n_11));
  nd12d1 g1992__9315(.A1 (n_6), .A2 (wr_addr[1]), .ZN (n_10));
  nd12d1 g1993__9945(.A1 (wr_addr[1]), .A2 (n_5), .ZN (n_9));
  nr02d1 g1995__2883(.A1 (wr_addr[1]), .A2 (n_6), .ZN (n_8));
  nd02d1 g1996__2346(.A1 (n_5), .A2 (wr_addr[1]), .ZN (n_7));
  nd12d1 g1997__1666(.A1 (n_4), .A2 (wr_addr[2]), .ZN (n_6));
  nr02d1 g1998__7410(.A1 (wr_addr[2]), .A2 (n_4), .ZN (n_5));
  nd12d1 g1999__6417(.A1 (full), .A2 (wr_en), .ZN (n_4));
  inv0d0 g2000(.I (wr_addr[3]), .ZN (n_3));
  inv0d0 g2001(.I (wr_addr[0]), .ZN (n_2));
  nd12d1 g2__5477(.A1 (n_9), .A2 (wr_addr[3]), .ZN (n_1));
  an12d1 g2002__2398(.A1 (wr_addr[3]), .A2 (n_8), .Z (n_0));
endmodule

module dff_41(clk, rst, wr_data, rd_data);
  input clk, rst;
  input [4:0] wr_data;
  output [4:0] rd_data;
  wire clk, rst;
  wire [4:0] wr_data;
  wire [4:0] rd_data;
  dfcrq1 \rd_data_reg[4] (.CDN (rst), .CP (clk), .D (wr_data[4]), .Q
       (rd_data[4]));
  dfcrq1 \rd_data_reg[3] (.CDN (rst), .CP (clk), .D (wr_data[3]), .Q
       (rd_data[3]));
  dfcrq1 \rd_data_reg[1] (.CDN (rst), .CP (clk), .D (wr_data[1]), .Q
       (rd_data[1]));
  dfcrq1 \rd_data_reg[0] (.CDN (rst), .CP (clk), .D (wr_data[0]), .Q
       (rd_data[0]));
  dfcrq1 \rd_data_reg[2] (.CDN (rst), .CP (clk), .D (wr_data[2]), .Q
       (rd_data[2]));
endmodule

module dff_40(clk, rst, wr_data, rd_data);
  input clk, rst;
  input [4:0] wr_data;
  output [4:0] rd_data;
  wire clk, rst;
  wire [4:0] wr_data;
  wire [4:0] rd_data;
  dfcrq1 \rd_data_reg[4] (.CDN (rst), .CP (clk), .D (wr_data[4]), .Q
       (rd_data[4]));
  dfcrq1 \rd_data_reg[3] (.CDN (rst), .CP (clk), .D (wr_data[3]), .Q
       (rd_data[3]));
  dfcrq1 \rd_data_reg[1] (.CDN (rst), .CP (clk), .D (wr_data[1]), .Q
       (rd_data[1]));
  dfcrq1 \rd_data_reg[0] (.CDN (rst), .CP (clk), .D (wr_data[0]), .Q
       (rd_data[0]));
  dfcrq1 \rd_data_reg[2] (.CDN (rst), .CP (clk), .D (wr_data[2]), .Q
       (rd_data[2]));
endmodule

module cdc_synchronizer_39(clk, rst, in_data, out_data);
  input clk, rst;
  input [4:0] in_data;
  output [4:0] out_data;
  wire clk, rst;
  wire [4:0] in_data;
  wire [4:0] out_data;
  wire [4:0] in_data_n;
  dff_41 dff_1(.clk (clk), .rst (rst), .wr_data (in_data), .rd_data
       (in_data_n));
  dff_40 dff_2(.clk (clk), .rst (rst), .wr_data (in_data_n), .rd_data
       (out_data));
endmodule

module reset_sync_43(clk, rst, rst_sync);
  input clk, rst;
  output rst_sync;
  wire clk, rst;
  wire rst_sync;
  wire rst_sync_reg_8;
  dfcrq1 rst_sync_reg(.CDN (rst), .CP (clk), .D (rst_sync_reg_8), .Q
       (rst_sync));
  dfcrq1 rst_sync_reg_reg(.CDN (rst), .CP (clk), .D (1'b1), .Q
       (rst_sync_reg_8));
endmodule

module dff(clk, rst, wr_data, rd_data);
  input clk, rst;
  input [4:0] wr_data;
  output [4:0] rd_data;
  wire clk, rst;
  wire [4:0] wr_data;
  wire [4:0] rd_data;
  dfcrq1 \rd_data_reg[4] (.CDN (rst), .CP (clk), .D (wr_data[4]), .Q
       (rd_data[4]));
  dfcrq1 \rd_data_reg[3] (.CDN (rst), .CP (clk), .D (wr_data[3]), .Q
       (rd_data[3]));
  dfcrq1 \rd_data_reg[1] (.CDN (rst), .CP (clk), .D (wr_data[1]), .Q
       (rd_data[1]));
  dfcrq1 \rd_data_reg[2] (.CDN (rst), .CP (clk), .D (wr_data[2]), .Q
       (rd_data[2]));
  dfcrq1 \rd_data_reg[0] (.CDN (rst), .CP (clk), .D (wr_data[0]), .Q
       (rd_data[0]));
endmodule

module dff_42(clk, rst, wr_data, rd_data);
  input clk, rst;
  input [4:0] wr_data;
  output [4:0] rd_data;
  wire clk, rst;
  wire [4:0] wr_data;
  wire [4:0] rd_data;
  dfcrq1 \rd_data_reg[4] (.CDN (rst), .CP (clk), .D (wr_data[4]), .Q
       (rd_data[4]));
  dfcrq1 \rd_data_reg[3] (.CDN (rst), .CP (clk), .D (wr_data[3]), .Q
       (rd_data[3]));
  dfcrq1 \rd_data_reg[1] (.CDN (rst), .CP (clk), .D (wr_data[1]), .Q
       (rd_data[1]));
  dfcrq1 \rd_data_reg[0] (.CDN (rst), .CP (clk), .D (wr_data[0]), .Q
       (rd_data[0]));
  dfcrq1 \rd_data_reg[2] (.CDN (rst), .CP (clk), .D (wr_data[2]), .Q
       (rd_data[2]));
endmodule

module cdc_synchronizer(clk, rst, in_data, out_data);
  input clk, rst;
  input [4:0] in_data;
  output [4:0] out_data;
  wire clk, rst;
  wire [4:0] in_data;
  wire [4:0] out_data;
  wire [4:0] in_data_n;
  dff dff_1(clk, rst, in_data, in_data_n);
  dff_42 dff_2(clk, rst, in_data_n, out_data);
endmodule

module reset_sync(clk, rst, rst_sync);
  input clk, rst;
  output rst_sync;
  wire clk, rst;
  wire rst_sync;
  wire rst_sync_reg_8;
  dfcrq1 rst_sync_reg(.CDN (rst), .CP (clk), .D (rst_sync_reg_8), .Q
       (rst_sync));
  dfcrq1 rst_sync_reg_reg(.CDN (rst), .CP (clk), .D (1'b1), .Q
       (rst_sync_reg_8));
endmodule

module fifo_top(wr_clk_pad, rd_clk_pad, wr_en_pad, rd_en_pad,
     wr_rst_pad, rd_rst_pad, wr_data_pad, rd_data_pad, empty_pad,
     full_pad);
  input wr_clk_pad, rd_clk_pad, wr_en_pad, rd_en_pad, wr_rst_pad,
       rd_rst_pad;
  input [7:0] wr_data_pad;
  output [7:0] rd_data_pad;
  output empty_pad, full_pad;
  wire wr_clk_pad, rd_clk_pad, wr_en_pad, rd_en_pad, wr_rst_pad,
       rd_rst_pad;
  wire [7:0] wr_data_pad;
  wire [7:0] rd_data_pad;
  wire empty_pad, full_pad;
  wire [4:0] wr_addr_grey_sync;
  wire [4:0] rd_addr_grey;
  wire [3:0] rd_addr;
  wire [4:0] rd_addr_grey_sync;
  wire [4:0] wr_addr_grey;
  wire [3:0] wr_addr;
  wire [7:0] wr_data;
  wire [7:0] rd_data;
  wire empty, full, rd_clk, rd_en, rd_rst, rd_rst_sync, read_clk,
       wr_clk;
  wire wr_en, wr_rst, wr_rst_sync, write_clk;
  fifo_empty e(rd_clk, rd_en, rd_rst_sync, wr_addr_grey_sync, empty,
       rd_addr_grey, rd_addr);
  fifo_full f(wr_clk, wr_en, wr_rst_sync, rd_addr_grey_sync, full,
       wr_addr_grey, wr_addr);
  fifo_memory m(wr_clk, wr_rst_sync, wr_en, full, wr_addr, rd_addr,
       wr_data, rd_data);
  cdc_synchronizer_39 rd_addr_sync(rd_clk, rd_rst_sync, wr_addr_grey,
       wr_addr_grey_sync);
  reset_sync_43 rd_sync(rd_clk, rd_rst, rd_rst_sync);
  cdc_synchronizer wr_addr_sync(wr_clk, wr_rst_sync, rd_addr_grey,
       rd_addr_grey_sync);
  reset_sync wr_sync(wr_clk, wr_rst, wr_rst_sync);
  pc3c01 pc3c01_1(.CCLK (read_clk), .CP (rd_clk));
  pc3c01 pc3c01_2(.CCLK (write_clk), .CP (wr_clk));
  pc3d01 pc3d01_1(.PAD (rd_clk_pad), .CIN (read_clk));
  pc3d01 pc3d01_2(.PAD (wr_clk_pad), .CIN (write_clk));
  pc3d01 pc3d01_3(.PAD (wr_rst_pad), .CIN (wr_rst));
  pc3d01 pc3d01_4(.PAD (rd_rst_pad), .CIN (rd_rst));
  pc3d01 pc3d01_5(.PAD (wr_en_pad), .CIN (wr_en));
  pc3d01 pc3d01_6(.PAD (rd_en_pad), .CIN (rd_en));
  pc3d01 pc3d01_7(.PAD (wr_data_pad[7]), .CIN (wr_data[7]));
  pc3d01 pc3d01_8(.PAD (wr_data_pad[6]), .CIN (wr_data[6]));
  pc3d01 pc3d01_9(.PAD (wr_data_pad[5]), .CIN (wr_data[5]));
  pc3d01 pc3d01_10(.PAD (wr_data_pad[4]), .CIN (wr_data[4]));
  pc3d01 pc3d01_11(.PAD (wr_data_pad[3]), .CIN (wr_data[3]));
  pc3d01 pc3d01_12(.PAD (wr_data_pad[2]), .CIN (wr_data[2]));
  pc3d01 pc3d01_13(.PAD (wr_data_pad[1]), .CIN (wr_data[1]));
  pc3d01 pc3d01_14(.PAD (wr_data_pad[0]), .CIN (wr_data[0]));
  pc3o05 pc3o05_1(.I (rd_data[7]), .PAD (rd_data_pad[7]));
  pc3o05 pc3o05_2(.I (rd_data[6]), .PAD (rd_data_pad[6]));
  pc3o05 pc3o05_3(.I (rd_data[5]), .PAD (rd_data_pad[5]));
  pc3o05 pc3o05_4(.I (rd_data[4]), .PAD (rd_data_pad[4]));
  pc3o05 pc3o05_5(.I (rd_data[3]), .PAD (rd_data_pad[3]));
  pc3o05 pc3o05_6(.I (rd_data[2]), .PAD (rd_data_pad[2]));
  pc3o05 pc3o05_7(.I (rd_data[1]), .PAD (rd_data_pad[1]));
  pc3o05 pc3o05_8(.I (rd_data[0]), .PAD (rd_data_pad[0]));
  pc3o05 pc3o05_9(.I (full), .PAD (full_pad));
  pc3o05 pc3o05_10(.I (empty), .PAD (empty_pad));
endmodule

