###############################################################
#  Generated by:      Cadence Innovus 21.18-s099_1
#  OS:                Linux x86_64(Host ID c2slab.cet.ac.in)
#  Generated on:      Thu Feb 27 20:59:18 2025
#  Design:            fifo_top
#  Command:           create_ccopt_clock_tree_spec -file ./Clock_Tree_Synthesis/fifo_top_ccopt.spec
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Innovus
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

if { [get_ccopt_clock_trees] != {} } {
  error {Cannot run clock tree spec: clock trees are already defined.}
}

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# The following pins are clock sources
set_ccopt_property cts_is_sdc_clock_root -pin rd_clk_pad true
set_ccopt_property cts_is_sdc_clock_root -pin wr_clk_pad true

# Clocks present at pin wr_clk_pad
#   write_clk (period 15.000ns) in timing_config all([/run/media/user1/c2s/S5_training_batch2/Vinayak3/07_Placement/Placement/fifo_top_placed.enc.dat/mmmc/modes/all/all.sdc])
create_ccopt_clock_tree -name write_clk -source wr_clk_pad -no_skew_group
set_ccopt_property target_max_trans_sdc -delay_corner max_delay -early -clock_tree write_clk 1.875
set_ccopt_property target_max_trans_sdc -delay_corner max_delay -late -clock_tree write_clk 3.000
# Clock tree offset inferred from set_clock_latency -source assertions:
set_ccopt_property source_latency -clock_tree write_clk 1.250
# Clock period setting for source pin of write_clk
set_ccopt_property clock_period -pin wr_clk_pad 15

# Clocks present at pin rd_clk_pad
#   read_clk (period 30.000ns) in timing_config all([/run/media/user1/c2s/S5_training_batch2/Vinayak3/07_Placement/Placement/fifo_top_placed.enc.dat/mmmc/modes/all/all.sdc])
create_ccopt_clock_tree -name read_clk -source rd_clk_pad -no_skew_group
set_ccopt_property target_max_trans_sdc -delay_corner max_delay -early -clock_tree read_clk 3.750
set_ccopt_property target_max_trans_sdc -delay_corner max_delay -late -clock_tree read_clk 6.000
# Clock tree offset inferred from set_clock_latency -source assertions:
set_ccopt_property source_latency -clock_tree read_clk 1.250
# Clock period setting for source pin of read_clk
set_ccopt_property clock_period -pin rd_clk_pad 30

##############################################################################
##
## Timing connectivity based skew groups: off
##
##############################################################################
set_ccopt_property timing_connectivity_info {}

# Skew group to balance non generated clock:read_clk in timing_config:all (sdc /run/media/user1/c2s/S5_training_batch2/Vinayak3/07_Placement/Placement/fifo_top_placed.enc.dat/mmmc/modes/all/all.sdc)
create_ccopt_skew_group -name read_clk/all -sources rd_clk_pad -auto_sinks
set_ccopt_property include_source_latency -skew_group read_clk/all true
set_ccopt_property extracted_from_clock_name -skew_group read_clk/all read_clk
set_ccopt_property extracted_from_constraint_mode_name -skew_group read_clk/all all
set_ccopt_property extracted_from_delay_corners -skew_group read_clk/all {max_delay min_delay}

# Skew group to balance non generated clock:write_clk in timing_config:all (sdc /run/media/user1/c2s/S5_training_batch2/Vinayak3/07_Placement/Placement/fifo_top_placed.enc.dat/mmmc/modes/all/all.sdc)
create_ccopt_skew_group -name write_clk/all -sources wr_clk_pad -auto_sinks
set_ccopt_property include_source_latency -skew_group write_clk/all true
set_ccopt_property extracted_from_clock_name -skew_group write_clk/all write_clk
set_ccopt_property extracted_from_constraint_mode_name -skew_group write_clk/all all
set_ccopt_property extracted_from_delay_corners -skew_group write_clk/all {max_delay min_delay}


check_ccopt_clock_tree_convergence
# Restore the ILM status if possible
if { [get_ccopt_property auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

